### ISSUE TITLE
Error Calculating Author Tag Cloud

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#12]
```
What steps will reproduce the problem?
1. python svnplot.py -v -r 300 /root/svnplot.sl3 /var/www/html/svnplot/

What is the expected output? What do you see instead?
Calculating subversion stat graphs                                        

Subversion log database : /root/svnplot.sl3                               

Graphs will generated in : /var/www/html/svnplot/                         

Repository Name : None                                                    

Search path inside repository : /%                                        

Graph thumbnail size : 100                                                

using default html template                                               

Set the search path to /                                                  

Calculating Activity by day of week graph                                 

/usr/lib/python2.6/site-packages/matplotlib/backends/backend_gtk.py:640:
DeprecationWarning: Use the new widget gtk.Tooltip    
  self.tooltips = gtk.Tooltips()                                          

Calculating Activity by time of day graph
Calculating Author Activity graph
Calculating Commit activity graph
Calculating Commit Activity Index by time of day graph
Calculating LoC graph
Calculating LoC and Churn graph
Calculating Developer Contribution graph
Calculating Average File Size graph
Calculating File Count graph
Calculating File Types graph
Calculating current Directory size pie graph
Calculating Directory size line graph
Calculating current Directory File Count pie graph
Calculating tag cloud for log messages
Calculating Author Tag Cloud
Traceback (most recent call last):
  File "svnplot.py", line 657, in <module>
    RunMain()
  File "svnplot.py", line 654, in RunMain
    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize)
  File "svnplot.py", line 244, in AllGraphs
    graphParamDict = self._getGraphParamDict( thumbsize)
  File "svnplot.py", line 589, in _getGraphParamDict
    graphParamDict["AuthCloud"] = self.AuthorCloud()
  File "svnplot.py", line 555, in AuthorCloud
    for auth, freq, actIdx in authTagList])
  File "svnplot.py", line 191, in getTagFontSize
    scalingFactor = fontsizevariation/(maxFreqLog-minFreqLog)
ZeroDivisionError: float division


What version of the product are you using? On what operating system?
SVNPlot 0.5.6 on Mandriva Linux Cooker


```

Original issue reported on code.google.com by `p.filip...@gmail.com` on 13 Jul 2009 at 8:18

**Comment by GoogleCodeExporter** [comment]
```
Just additional information - I think the problem is created by the fact that 
folder
has only one committer, so maxFreqLog=minFreqLog

I patched that line to take into account maxFreqLog=minFreqLog, but it stops 
elsewhere:
Calculating Author Tag Cloud                                                    


Traceback (most recent call last):                                              


  File "svnplot.py", line 660, in <module>                                          

    RunMain()                                                                       

  File "svnplot.py", line 657, in RunMain                                           

    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize)              

  File "svnplot.py", line 247, in AllGraphs                                         

    graphParamDict = self._getGraphParamDict( thumbsize)                            

  File "svnplot.py", line 592, in _getGraphParamDict                                

    graphParamDict["AuthCloud"] = self.AuthorCloud()                                

  File "svnplot.py", line 558, in AuthorCloud                                       

    for auth, freq, actIdx in authTagList])                                         

  File "svnplot.py", line 203, in getActivityClr                                    

    clrStr=mpl.colors.rgb2hex(rgbclr[0:3])                                          

  File "/usr/lib/python2.6/site-packages/matplotlib/colors.py", line 221, in rgb2hex

    return '#%02x%02x%02x' % tuple([round(val*255) for val in rgb])                 

TypeError: only length-1 arrays can be converted to Python scalars  

```

Original comment by `p.filip...@gmail.com` on 13 Jul 2009 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the error report. I have fixed the error. Please take the latest 
svnplot.py from the repository. 
(http://code.google.com/p/svnplot/source/browse/trunk/src/svnplot/svnplot.py)

The fix will be included in next release.
```

Original comment by `nitinbh...@gmail.com` on 14 Jul 2009 at 2:38
- Changed state: **Fixed**
