### ISSUE TITLE
Does svnplot work with remote svn not using apache?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#13]
```
We have an SVN system that we access directly via the svn protocol (tcp
port 3690).

I cannot run svnplot on the svn server itself because the system only has
python 2.4 on it (CentOS 5.3 X86_64) and it seems this app requires at
least 2.5.

I've tried to run the command: /opt/SVNPlot-0.5.6$ sudo python
./svnplot/svnlog2sqlite.py -l svn://subdomain.domain.com/var/svn
/opt/SVNPlot-0.5.6/sqlite3db/svn and get the error:

Updating the subversion log
Repository : svn://subdomain.domain.com/var/svn
Log database filepath : /opt/SVNPlot-0.5.6/sqlite3db/svn
Update Changed Line Count : True
ERROR:root:Error Repository Root not found
Error Repository Root not found
Traceback (most recent call last):
  File "./svnplot/svnlog2sqlite.py", line 39, in convert
    headrev = self.svnclient.getHeadRevNo()
  File "/opt/SVNPlot-0.5.6/svnplot/svnlogiter.py", line 116, in getHeadRevNo
    headrev = self._getHeadRev()
  File "/opt/SVNPlot-0.5.6/svnplot/svnlogiter.py", line 127, in _getHeadRev
    rooturl = self.getRootUrl()
  File "/opt/SVNPlot-0.5.6/svnplot/svnlogiter.py", line 340, in getRootUrl
    raise RuntimeError , "Repository Root not found"
RuntimeError: Repository Root not found

The system is also password protected.

Is there any way I can run svnplot against this configuration? The
quickstart guide says "<svnrepo url> can be any repository format supported
by Subverson" but I'm not having much luck.

SVNPlot-0.5.6 is installed on Ubuntu 9.04 server amd64, and the server is
on the same subnet as the SVN server.

Thanks in advance,

Alan
```

Original issue reported on code.google.com by `acho...@gmail.com` on 17 Jul 2009 at 8:29

**Comment by GoogleCodeExporter** [comment]
```
Alan,

It should work with remote svn repositories with svn protocol. 
The repository root path detection in released version is still having some 
problems. I had to add my own logic since the repository root detection 
function in PySVN crashed python interpreter. I will check if this bug is fixed.

Meanwhile there is a updated (and I think simpler version of svn root path 
detection) is available in svn repository. Please get the latest version from 
trunk and give it a try.

Thanks for the bug report. 
regards,
Nitin
```

Original comment by `nitinbh...@gmail.com` on 18 Jul 2009 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
please test on the current release (0.5.7). The repository root path detection 
and updating line count is improved.
```

Original comment by `nitinbh...@gmail.com` on 20 Jul 2009 at 5:42

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 28 Jul 2009 at 2:31

**Comment by GoogleCodeExporter** [comment]
```
Same problem with release 0.6.1. Cannot connect with svn:// schema in a password
protected repository. Output follows:

Error 
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 45, in convert
    rootUrl = self.svnclient.getRootUrl()
  File "/home/abraham/tmp/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 399, in getRootUrl
    self.getRootUrl2()
  File "/home/abraham/tmp/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 373, in getRootUrl2
    assert(len(changepathlist) > 0)
AssertionError
Trying again (1)
Error 
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 45, in convert
    rootUrl = self.svnclient.getRootUrl()
  File "/home/abraham/tmp/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 399, in getRootUrl
    self.getRootUrl2()
  File "/home/abraham/tmp/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 373, in getRootUrl2
    assert(len(changepathlist) > 0)
AssertionError
Trying again (2)
Error 
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 45, in convert
    rootUrl = self.svnclient.getRootUrl()
  File "/home/abraham/tmp/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 399, in getRootUrl
    self.getRootUrl2()
  File "/home/abraham/tmp/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 373, in getRootUrl2
    assert(len(changepathlist) > 0)
AssertionError
Trying again (3)
```

Original comment by `abraham....@gmail.com` on 24 May 2010 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
I have added option -u and -p to specify the username and password on the 
command line. Please check if that works. 

I don't have access to any svnserve based repository. If above option doesnot 
work, then I will create a svnserve based test repository.
```

Original comment by `nitinbh...@gmail.com` on 30 May 2010 at 4:41

**Comment by GoogleCodeExporter** [comment]
```
the changes are available in trunk.
```

Original comment by `nitinbh...@gmail.com` on 30 May 2010 at 4:44

**Comment by GoogleCodeExporter** [comment]
```
Confirmed that version 0.7.6 works fine against svn:// protocol.
```

Original comment by `j...@jeffvstein.org` on 13 Jan 2012 at 6:27

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 14 Jan 2012 at 7:37
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 14 Jan 2012 at 7:38
- Changed state: **Verified**
