### ISSUE TITLE
I would need a installation guide to set up the SVN PLOT Report

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#14]
```
What steps will reproduce the problem?
1. I have installed Python3.0.1 but i could not install the numpy here.
2. how do you install matplotlib ?
3.  Could you please explain in detail step to install the SVN PLOT i tried
so many times i could not able to install the SVN PLot completely 

What is the expected output? What do you see instead?

I m getting SYNTAX ERROR 
What version of the product are you using? On what operating system?
SVNPLOT 0.5.8

Please provide any additional information below.


```

Original issue reported on code.google.com by `gopinath...@gmail.com` on 27 Jul 2009 at 5:12

**Comment by GoogleCodeExporter** [comment]
```
There are many syntax changes in Python 3.x from 2.x. Hence NumPy is not yet 
available for Python 2.x. You will need to install Python 2.5 or Python 2.6. 

For SVNPlot install, you will need to install following packages before 
installing svnplot. Make sure that you are using using packages for appropriate 
for Python version.

1. PySVN - http://pysvn.tigris.org/project_downloads.html (e.g. 
http://pysvn.tigris.org/files/documents/1233/45666/py26-pysvn-svn161-1.7.0-1177.
exe is for Pysvn version 1.17 for Python 2.6 and Subversion 1.61 for windows

2. NumPy - http://sourceforge.net/projects/numpy/files/

3. Matplotlib - Check the installation instruction 
(http://matplotlib.sourceforge.net/users/installing.html). You can download 
installation packages from http://sourceforge.net/projects/matplotlib/files/

Then install SVNPlot.

You have to run svnlog2sqlite.py to create the database first and then run 
svnplot.py to generate the graphs. Check the introduction page for more details 
on running svnlog2sqlite.py and svnplot.py

```

Original comment by `nitinbh...@gmail.com` on 28 Jul 2009 at 2:21

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your comments and you said 
Hence NumPy is not yet available for Python 2.x.(Its python3.x or 2.x does not 
support numpy ? ) You will need to install Python 2.5 or Python 2.6. 
I m testing in the Linux environment so i have installed 3.0 so when i check 
the 
version for python it shows the latest one which i installed ? i m new to linux 
environment can u pls tell how to uninstall the python 3.0 so that i can 
install the 
2.5 and try the same. i m not able to install the numpy and pysvn in the Redhat 
linux whenever i tried it throws an error message as " SYNTAX ERROR "

Thanks,
Gopinath.M
```

Original comment by `gopinath...@gmail.com` on 28 Jul 2009 at 8:32

**Comment by GoogleCodeExporter** [comment]
```
First my mistake. NumPy is not available for 3.x. It is available for Python 
2.5 and
2.6. 

I am also new to Linux. So not sure how to do that. I think you will get the 
info on
how to uninstall Python rpm from google search.

NumPy and PySVN make sure that you are installing binaries appropriate for 
python
version installed.
```

Original comment by `nitinbh...@gmail.com` on 28 Jul 2009 at 9:58

**Comment by GoogleCodeExporter** [comment]
```
whether Ubuntu linux will support the SVN Plot ? and also i need to know how to
create a sqllite DB for converting svnlogs into sql db file. DO i need to create
manually the db name in sqlite and place the same while running this script
svnlog2sqlite.py or this python script will automatically create  the sqllite db
please address me on the same . we have planned to install and configure the 
SVNPLOT.
Once i installed python then i need to install the pysvn and numpy and also
matplotlib files one by one and then only i should install the svnplot am i 
right ?
```

Original comment by `gopinath...@gmail.com` on 28 Jul 2009 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
>>whether Ubuntu linux will support the SVN Plot ?
Some developers have tried svnplot on linux. So it works on linux.

>>also i need to know how to create a sqllite DB for converting svnlogs into 
sql db file.
No. svnlog2sqlite will do all the necessary db creation.

After all the installation is done, you need to do only two steps. (a) call 
svnlog2sqlite for creation/updation of database. (b) call svnplot.py to 
generate the graphs.
```

Original comment by `nitinbh...@gmail.com` on 29 Jul 2009 at 2:30

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your comments and i ll proceed to install and configure the files 
and let 
you know if i find any issues while installation.
```

Original comment by `gopinath...@gmail.com` on 29 Jul 2009 at 9:43

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I found the following error while installing pysvn 
Info: Found  PyCXX include in /home/pysvn-1.7.0/pysvn-1.7.0/Import/pycxx-5.5.0
Info: Found   PyCXX Source in /home/pysvn-1.7.0/pysvn-1.7.0/Import/pycxx-
5.5.0/S                                                                         

                   rc
Info: Found Python include in /home/pysvn-1.7.0/pysvn-1.7.0/Import/pycxx-
5.5.0 /                                                                         

                   home/pysvn-1.7.0/pysvn-1.7.0/Import/pycxx-
5.5.0/Src /usr/local/include/python2.6
('Error:', 'cannot find SVN include svn_client.h - use --svn-inc-dir=')

what do i need to do resolve this erro please address me on the same

Thanks,
Gopinath.M
```

Original comment by `gopinath...@gmail.com` on 30 Jul 2009 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
Looks like you are compiling PySVN. I think already compiled rpms should be 
available for the linux version that you are using. Please and download the 
binaries directly if possible.
```

Original comment by `nitinbh...@gmail.com` on 30 Jul 2009 at 7:53

**Comment by GoogleCodeExporter** [comment]
```
hi,
I installed pysvn using yum install pysvn and the i have installed all the 
supporting files like matplotlib,numpy,and svnplot. i have got the following 
error 
while running the svnlog2sqllite.py

[root@svnreport svnplot]# python svnlog2sqlite.py 
http://svnplot.googlecode.com/ 
svn/ /root
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 18, in <module>
    import svnlogiter
  File "/root/SVNPLOT INSTALLATION FILES/svnplot/SVNPlot-
0.5.8/svnplot/svnlogiter.py", line 16, in <module>
    import pysvn
ImportError: No module named pysvn
please explain me how to run the reports.

Thanks,
Gopinath

```

Original comment by `gopinath...@gmail.com` on 30 Jul 2009 at 11:28

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I converted the svnlogs into sqlitedb but when i run svnplot.py i ll get this 
error 

Traceback (most recent call last):
  File "svnplot.py", line 41, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python2.5/site-packages/matplotlib/pyplot.py", line 37, in <module>
    new_figure_manager, draw_if_interactive, show = pylab_setup()
  File "/usr/lib/python2.5/site-packages/matplotlib/backends/__init__.py", line 24, 
in pylab_setup
    globals(),locals(),[backend_name])
  File "/usr/lib/python2.5/site-packages/matplotlib/backends/backend_gtkagg.py", 
line 10, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, 
FigureCanvasGTK,\
  File "/usr/lib/python2.5/site-packages/matplotlib/backends/backend_gtk.py", line 
7, in <module>
    import gtk; gdk = gtk.gdk
  File "/usr/lib/python2.5/site-packages/gtk-2.0/gtk/__init__.py", line 79, in 
<module>
    _init()
  File "/usr/lib/python2.5/site-packages/gtk-2.0/gtk/__init__.py", line 67, in _init
    _gtk.init_check()
RuntimeError: could not open display

Thanks,
Gopinath.M
```

Original comment by `gopinath...@gmail.com` on 31 Jul 2009 at 12:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 4 Feb 2010 at 5:17
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Use svnplot-js.py (javascript version). This one don't need NumPy and Matplotlib
```

Original comment by `nitinbh...@gmail.com` on 14 Dec 2010 at 8:06
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I have followed the instructions with Python 2.7.1 on Windows, but it still 
does not work. I am getting:
"sqlite3.OperationalError: unable to open database file"

Is there any magic I still have to do with the thing named "sqlite3"? I just 
used some path on my computer were no files were so far.

Is it really not possible to provide a single executable when programming in 
Python? Installing all these dependencies is a real hell.
```

Original comment by `mcz...@poczta.onet.pl` on 8 Jun 2011 at 5:26

**Comment by GoogleCodeExporter** [comment]
```
Ok, I finally managed to make it work - provide a path to a non-existing file 
instead of a path to an empty directiory.
```

Original comment by `avsmem...@future-processing.com` on 8 Jun 2011 at 7:22
