### ISSUE TITLE
Key Error on line 366 in svnlogiter.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#22]
```
dump is below. looked at the log message on the revision in question and it 
looked okay, 
appears to have no weird UTF. was able to get the script to keep running if I 
added a catch for 
the KeyError exception around line 366 but I am not sure what the error is.

ERROR:root:Error u'\u221a'
Error u'\u221a'
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 42, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 87, in ConvertRevs
    addedfiles, changedfiles, deletedfiles = revlog.changedFileCount(bChkIfDir)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 454, in changedFileCount
    isdir = self.isDirectory(change)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 474, in isDirectory
    isDir = self.logclient.isDirectory(revno, path, action)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 278, in isDirectory
    entry = self.getInfo(changepath, revno)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 230, in getInfo
    url = self.getUrl(path)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 366, in getUrl
    url = self.getRootUrl() + urllib.pathname2url(path)
  File "/usr/lib/python2.5/urllib.py", line 60, in pathname2url
    return quote(pathname)
  File "/usr/lib/python2.5/urllib.py", line 1205, in quote
    res = map(safe_map.__getitem__, s)
KeyError: u'\u221a'



```

Original issue reported on code.google.com by `ali.asa...@gmail.com` on 28 Dec 2009 at 9:43

**Comment by GoogleCodeExporter** [comment]
```
thanks for the bug report. I will check it. Is there any public repository 
where this error can be reproduced ?
```

Original comment by `nitinbh...@gmail.com` on 29 Dec 2009 at 1:21

**Comment by GoogleCodeExporter** [comment]
```
unfortunately, i don't know of a public repo that has this error so feel free 
to close this bug as "can not replicate" 
-- it would be neat if we could make a test harness that would run svnplot 
against many public repos as test 
cases. not sure if you do this already.
```

Original comment by `ali.asa...@gmail.com` on 29 Dec 2009 at 4:33

**Comment by GoogleCodeExporter** [comment]
```
please try changing the line 366 in svnlogiter.py from
             url = self.getRootUrl() + urllib.pathname2url(path)

to
     url = self.getRootUrl() + urllib.pathname2url(path.encode('utf8'))

I am not complete sure if this is 'correct' fix. But I think it will work. 
Based on your experience i will update the code.

```

Original comment by `nitinbh...@gmail.com` on 3 Jan 2010 at 8:55

**Comment by GoogleCodeExporter** [comment]
```
Yep that worked. Thanks.

I looked closely at the URL in question and it was an embedded Wordpress 
install that contained UTF in the 
URL for internationalization. Gotta love those Python UTF-8 issues.

Thanks again, nitinbhide. Love SVN Plot.


Here is the proof that it works now:

user@xxxx:/var/www/svnplot/SVNPlot-0.5.12/svnplot# python svnlog2sqlite.py -l 
-v svn://xxx/trunk/ 
./test.db 
Updating the subversion log
Repository : svn://xxx/trunk/
Log database filepath : ./test.db
Update Changed Line Count : True
Root url found : svn://xxxx
Start-End Rev no : 3-5247
converting revision 1340
ERROR:root:Error u'\u221a'
Error u'\u221a'
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 42, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 87, in ConvertRevs
    addedfiles, changedfiles, deletedfiles = revlog.changedFileCount(bChkIfDir)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 454, in changedFileCount
    isdir = self.isDirectory(change)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 474, in isDirectory
    isDir = self.logclient.isDirectory(revno, path, action)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 278, in isDirectory
    entry = self.getInfo(changepath, revno)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 230, in getInfo
    url = self.getUrl(path)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 366, in getUrl
    url = self.getRootUrl() + urllib.pathname2url(path)
  File "/usr/lib/python2.5/urllib.py", line 60, in pathname2url
    return quote(pathname)
  File "/usr/lib/python2.5/urllib.py", line 1205, in quote
    res = map(safe_map.__getitem__, s)
KeyError: u'\u221a'
Trying again (1)
Root url found : svn://xxx
Start-End Rev no : 3-5247
converting revision 1340
ERROR:root:Error u'\u221a'
Error u'\u221a'
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 42, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 87, in ConvertRevs
    addedfiles, changedfiles, deletedfiles = revlog.changedFileCount(bChkIfDir)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 454, in changedFileCount
    isdir = self.isDirectory(change)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 474, in isDirectory
    isDir = self.logclient.isDirectory(revno, path, action)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 278, in isDirectory
    entry = self.getInfo(changepath, revno)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 230, in getInfo
    url = self.getUrl(path)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 366, in getUrl
    url = self.getRootUrl() + urllib.pathname2url(path)
  File "/usr/lib/python2.5/urllib.py", line 60, in pathname2url
    return quote(pathname)
  File "/usr/lib/python2.5/urllib.py", line 1205, in quote
    res = map(safe_map.__getitem__, s)
KeyError: u'\u221a'
Trying again (2)
Root url found : svn://xxx
Start-End Rev no : 3-5247
converting revision 1340
ERROR:root:Error u'\u221a'
Error u'\u221a'
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 42, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 87, in ConvertRevs
    addedfiles, changedfiles, deletedfiles = revlog.changedFileCount(bChkIfDir)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 454, in changedFileCount
    isdir = self.isDirectory(change)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 474, in isDirectory
    isDir = self.logclient.isDirectory(revno, path, action)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 278, in isDirectory
    entry = self.getInfo(changepath, revno)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 230, in getInfo
    url = self.getUrl(path)
  File "/var/www/svnplot/SVNPlot-0.5.12/svnplot/svnlogiter.py", line 366, in getUrl
    url = self.getRootUrl() + urllib.pathname2url(path)
  File "/usr/lib/python2.5/urllib.py", line 60, in pathname2url
    return quote(pathname)
  File "/usr/lib/python2.5/urllib.py", line 1205, in quote
    res = map(safe_map.__getitem__, s)
KeyError: u'\u221a'
Trying again (3)
root@wellington:/var/www/svnplot/SVNPlot-0.5.12/svnplot# vim 
svnlogiter.pyxxxx@xxx:/var/www/svnplot/SVNPlot-0.5.12/svnplot# python 
svnlog2sqlite.py -l -v 
svn://wellington.well.lan/trunk/ ./test.db 
Updating the subversion log
Repository : svn://xxxx/trunk/
Log database filepath : ./test.db
Update Changed Line Count : True
Root url found : svn://wellington.well.lan
Start-End Rev no : 3-5247
converting revision 1340
converting revision 1341
converting revision 1342
converting revision 1343
converting revision
```

Original comment by `ali.asa...@gmail.com` on 3 Jan 2010 at 6:57

**Comment by GoogleCodeExporter** [comment]
```
Thanks. I will update the fix the svnplot source. It will be available in the 
next release. After that I will close the issue.
```

Original comment by `nitinbh...@gmail.com` on 4 Jan 2010 at 4:42
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in revision 246. Will be release in next releas (possibly 0.5.13)
```

Original comment by `nitinbh...@gmail.com` on 4 Jan 2010 at 8:35
- Changed state: **Fixed**
