### ISSUE TITLE
Generate Graph on a server which have no X server

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#23]
```
What steps will reproduce the problem?
1. Install svnplot on a serveur which has no X server
2. launch svnplot.py

What is the expected output? What do you see instead?
Cannot connect to DISPLAY

What version of the product are you using? On what operating system?
Trunk, R246
Linux Ubuntu Server

Thx
Changi
```

Original issue reported on code.google.com by `chang...@gmail.com` on 4 Feb 2010 at 8:08
- Merged into: #26

**Comment by GoogleCodeExporter** [comment]
```
svnplot.py does not any X Window calls. Its a command line application. The 
output png images/HTML files will be created in the given output directory. 

I am little confused what the exact problem. Please give more details.
```

Original comment by `nitinbh...@gmail.com` on 4 Feb 2010 at 4:18

**Comment by GoogleCodeExporter** [comment]
```
I think it's matplotlib : 

root@localhost:#python svnplot.py -n "4.X" tw.branches.sqlite3 /home/two/stats
/www/branches/4.x.bis/
connect localhost port 6010: Connection refused
Traceback (most recent call last):
  File "svnplot.py", line 721, in <module>
    RunMain()
  File "svnplot.py", line 718, in RunMain
    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize,
options.maxdircount)
  File "svnplot.py", line 232, in AllGraphs
    self.ActivityByWeekday(self._getGraphFileName(dirpath, "ActByWeek"))
  File "svnplot.py", line 264, in ActivityByWeekday
    ax = self._drawBarGraph(data, labels,0.5)
  File "/home/changi/test/svnplot-read-only/src/svnplot/svnplotbase.py", line 74, in
_drawBarGraph
    fig = plt.figure()
  File "/usr/lib/pymodules/python2.6/matplotlib/pyplot.py", line 254, in figure
    **kwargs)
  File "/usr/lib/pymodules/python2.6/matplotlib/backends/backend_tkagg.py", line 90,
in new_figure_manager
    window = Tk.Tk()
  File "/usr/lib/python2.6/lib-tk/Tkinter.py", line 1646, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive,
wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:11.0"
```

Original comment by `chang...@gmail.com` on 8 Feb 2010 at 1:17

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 13 Feb 2010 at 3:08
- Changed state: **Duplicate**
