### ISSUE TITLE
AttributeError: Subplot instance has no attribute 'set_color_cycle'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#35]
```
svnplot.py -v --dpi 70 -p /home/ubuntu/svnplot-read-
only/src/svnplot/svnplot-long.tmpl -n "MyRepo" /home/ubuntu/svnplot 
/home/ubuntu/svnplotgraphs
Calculating subversion stat graphs
Subversion log database : /home/ubuntu/svnplot
Graphs will generated in : /home/ubuntu/svnplotgraphs
Repository Name : MyRepo
Search path inside repository : /%
Graph thumbnail size : 100
Maximum dir count: 10
using template : /home/ubuntu/svnplot-read-only/src/svnplot/svnplot-
long.tmpl
Set the search path to /
Calculating Activity by day of week graph
Calculating Activity by time of day graph
Calculating Author Activity graph
Traceback (most recent call last):
  File "svnplot.py", line 721, in <module>
    RunMain()
  File "svnplot.py", line 718, in RunMain
    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize, 
options.maxdircount)
  File "svnplot.py", line 234, in AllGraphs
    self.AuthorActivityGraph(self._getGraphFileName(dirpath, 
"AuthActivity"))
  File "svnplot.py", line 383, in AuthorActivityGraph
    ax = self._drawStackedHBarGraph(dataList, authlabellist, legendlist, 
barwid)
  File "/usr/lib/python2.5/site-packages/svnplot/svnplotbase.py", line 117, 
in _drawStackedHBarGraph
    ax.set_color_cycle(self.clrlist)
AttributeError: Subplot instance has no attribute 'set_color_cycle'
```

Original issue reported on code.google.com by `sean.o...@gmail.com` on 13 Mar 2010 at 5:55

**Comment by GoogleCodeExporter** [comment]
```
Had wrong version of matplotlib
```

Original comment by `sean.o...@gmail.com` on 16 Mar 2010 at 12:59

**Comment by GoogleCodeExporter** [comment]
```
version mismatch. no code change required.
```

Original comment by `nitinbh...@gmail.com` on 16 Mar 2010 at 4:57
- Changed state: **Verified**
