### ISSUE TITLE
"No repository found" error when repository root is given

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#38]
```
Consider a repository called MyRepository that contains no trunk, branch or
tag directories. When I try to access said repository using something like
this:

svnlog2sqlite.py -l svn://localhost/MyRepository C:\REPODB.SQL

I get an error that looks like this:

--- begin error excerpt ---
ERROR:root:Error No repository found in 'svn://localhost'
Error No repository found in 'svn://localhost'
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\svnplot\svnlog2sqlite.py", line 47,
in convert
    (startrevno, endrevno) = self.svnclient.findStartEndRev()
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 168, in
findStartEndRev
    headrev = self._getHeadRev()
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 156, in
_getHeadRev
    revision_start=headrev, revision_end=headrev, discover_changed_paths=False)
ClientError: No repository found in 'svn://localhost'
Trying again (1)
...
--- end error excerpt ---

I can avoid the error by issuing the following command instead:

svnlog2sqlite.py -l svn://localhost/MyRepository/. C:\REPODB.SQL

It seems to me it should work either way: with or without the extra /.
after MyRepository.
```

Original issue reported on code.google.com by `adrianlo...@gmail.com` on 22 Apr 2010 at 2:27

**Comment by GoogleCodeExporter** [comment]
```
for http:// repositories repository root ending with or without '/' works. This 
seems to be a problem for svn:// repositories. I will try to test it on svn:// 
repositories.
```

Original comment by `nitinbh...@gmail.com` on 4 May 2010 at 7:05

**Comment by GoogleCodeExporter** [comment]
```
does not work with file:// protocol also
```

Original comment by `martin.m...@gmail.com` on 24 Aug 2010 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
I will check again.
```

Original comment by `nitinbh...@gmail.com` on 25 Aug 2010 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
Please try the latest code in /trunk
```

Original comment by `nitinbh...@gmail.com` on 25 Aug 2010 at 6:22

**Comment by GoogleCodeExporter** [comment]
```
great, it works
I tested file://.
```

Original comment by `martin.m...@gmail.com` on 25 Aug 2010 at 7:00

**Comment by GoogleCodeExporter** [comment]
```
fixed in trunk. Will be available in next release. (possibly 0.6.2 or 0.7.0)
```

Original comment by `nitinbh...@gmail.com` on 8 Sep 2010 at 7:35
- Changed state: **Fixed**
