### ISSUE TITLE
Error when trying to plot empty repos

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#45]
```
If there are no commits int svn tree, svnplot gives this error:
Updating the subversion log
Repository : file:///var/svn/adi
Log database filepath : adi.db
Update Changed Line Count : True
ERROR:root:Error No such revision 1
Error No such revision 1
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 45, in convert
    rootUrl = self.svnclient.getRootUrl()
  File "/home/alex/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 399, in getRootUrl
    self.getRootUrl2()
  File "/home/alex/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 366, in getRootUrl2
    revlog = self.svnclient.log(possibleroot, limit=1,discover_changed_paths=True)
ClientError: No such revision 1
Trying again (1)
ERROR:root:Error No such revision 1
Error No such revision 1
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 45, in convert
    rootUrl = self.svnclient.getRootUrl()
  File "/home/alex/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 399, in getRootUrl
    self.getRootUrl2()
  File "/home/alex/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 366, in getRootUrl2
    revlog = self.svnclient.log(possibleroot, limit=1,discover_changed_paths=True)
ClientError: No such revision 1
Trying again (2)
ERROR:root:Error No such revision 1
Error No such revision 1
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 45, in convert
    rootUrl = self.svnclient.getRootUrl()
  File "/home/alex/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 399, in getRootUrl
    self.getRootUrl2()
  File "/home/alex/SVNPlot-0.6.1/svnplot/svnlogiter.py", line 366, in getRootUrl2
    revlog = self.svnclient.log(possibleroot, limit=1,discover_changed_paths=True)
ClientError: No such revision 1
Trying again (3)
Traceback (most recent call last):
  File "svnplot-js.py", line 941, in <module>
    RunMain()
  File "svnplot-js.py", line 934, in RunMain
    svnstats = SVNStats(svndbpath)     
  File "/home/alex/SVNPlot-0.6.1/svnplot/svnstats.py", line 184, in __init__
    self.initdb()
  File "/home/alex/SVNPlot-0.6.1/svnplot/svnstats.py", line 208, in initdb
    self.__startDate = (datetime.datetime.strptime(row[0], "%Y-%m-%d %H:%M:%S")-onedaydiff).date()
TypeError: strptime() argument 1 must be string, not None
```

Original issue reported on code.google.com by `alex%sta...@gtempaccount.com` on 10 Oct 2010 at 5:50

**Comment by GoogleCodeExporter** [comment]
```
I will add proper error message. Will be available in the next release. 
(probably in another 2 weeks time.)
Thanks for the report.
```

Original comment by `nitinbh...@gmail.com` on 11 Oct 2010 at 3:52
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 30 Dec 2010 at 5:15
