### ISSUE TITLE
Found Error expected a character buffer object

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#48]
```
Error from svnlog2sqlite.py:

  Number revisions converted : 400 (Rev no : 1175)
  Found Error expected a character buffer object

After re-trying this aborts the run.

The change in question doesn't look too interesting. It was some adds, some 
deletes, and changes of files without anything out of the ordinary. There was a 
mixture of source (shell script) and data files (.tar.gz) I suppose.

From the log file:

2010-11-27 15:58:38,303 ERROR Found Error expected a character buffer object
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 56, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 115, in ConvertRevs
    for revlog in svnloglist:
  File "/root/svnplot-read-only/src/svnplot/svnlogiter.py", line 540, in next
    svnrevlog = SVNRevLog(self.logclient, revlog)
  File "/root/svnplot-read-only/src/svnplot/svnlogiter.py", line 710, in __init__
    self.__updateCopyFromPaths()
  File "/root/svnplot-read-only/src/svnplot/svnlogiter.py", line 756, in __updateCopyFromPaths
    change['copyfrom_path'] = curfilepath.replace(curpath, copyfrompath,1)

Version is from SVN, updated a couple of days ago.
```

Original issue reported on code.google.com by `sam.jan...@gmail.com` on 28 Nov 2010 at 5:17

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. This seems to be bug in the recent changes. Please give 
me 2/3 days.
```

Original comment by `nitinbh...@gmail.com` on 29 Nov 2010 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
can you add some print/logging.debug statements just before line 756 in 
svnlogiter.py and see what is the type printed for the varibles in the log file

logging.debug("type of curfilepath %s" % type(curfilepath))
logging.debug("value of curfilepath %s" % curfilepath)
logging.debug("type of curpath %s" % type(curpath))
logging.debug("value of curpath %s" % curpath)
logging.debug("type of copyfrompath %s" % type(copyfrompath))
logging.debug("value of copyfrompath %s" % copyfrompath)


```

Original comment by `nitinbh...@gmail.com` on 29 Nov 2010 at 10:48

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 30 Nov 2010 at 1:31
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in trunk. Please check. 
```

Original comment by `nitinbh...@gmail.com` on 30 Nov 2010 at 1:39

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the quick feedback!

Not quite there just yet. I've just checked again, and then also added 
debugging as requested as it didn't quite work.

The error is now:

2010-11-30 15:25:42,255 DEBUG Trying to get revision logs [1176:7999]
2010-11-30 15:25:43,355 ERROR Found Error coercing to Unicode: need string or 
buffer, NoneType found
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 56, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 115, in ConvertRevs
    for revlog in svnloglist:
  File "/root/svnplot-read-only/src/svnplot/svnlogiter.py", line 550, in next
    svnrevlog = SVNRevLog(self.logclient, revlog)
  File "/root/svnplot-read-only/src/svnplot/svnlogiter.py", line 721, in __init__
    self.__updateCopyFromPaths()
  File "/root/svnplot-read-only/src/svnplot/svnlogiter.py", line 767, in __updateCopyFromPaths
    change['copyfrom_path'] = curfilepath.replace(curpath, copyfrompath,1)
TypeError: coercing to Unicode: need string or buffer, NoneType found

When I added some logging, I could see earlier that "copyfrom_path" is None:

2010-11-30 15:26:43,339 DEBUG type of curpath <type 'unicode'>
2010-11-30 15:26:43,339 DEBUG value of curpath /trunk/...blah...
2010-11-30 15:26:43,339 DEBUG type of copyfrom_path <type 'NoneType'>
2010-11-30 15:26:43,339 DEBUG value of copyfrom_path None

Would any further information be of assistance?
```

Original comment by `sam.jan...@gmail.com` on 30 Nov 2010 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
Please try the latest changes in trunk. 

I could not reproduce these errors. I am making changes reviewing the code and 
looking at the error messages/logs. Hence it is taking time and multiple 'try 
now' requests to you. 
```

Original comment by `nitinbh...@gmail.com` on 1 Dec 2010 at 5:29

**Comment by GoogleCodeExporter** [comment]
```
I ran into exactly the same "coercing to Unicode" problem over night. Simply 
restarting the DB-build where it left off did not work, neither with yesterdays 
version nor with your current trunk.

tail: svnlog2sqlite.log: file truncated
2010-12-01 08:40:47,010 ERROR Found Error
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 416, in RunMain
    conv.convert(svnrevstartdate, svnrevenddate, options.updlinecount)
  File "svnlog2sqlite.py", line 47, in convert
    self.CreateTables()
  File "svnlog2sqlite.py", line 294, in CreateTables
    self.__fixPaths()
  File "svnlog2sqlite.py", line 306, in __fixPaths
    logging.debug("fixing path for %s to %s"%(path, nrmpath))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 29: 
ordinal not in range(128)

I now restartet the process with a fresh DB, but it will take several hours 
until it reaches the revision in question.
```

Original comment by `G.Ohr...@web.de` on 1 Dec 2010 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
sorry for the trouble. since I cannot reproduce these errors, I am kind of 
debugging based on 'hunch' and trying out different things.

The errors seem be because of 'non -ascii' characters in filenames. Can you 
create a test repository with such file names and try on it. It may be faster. 

```

Original comment by `nitinbh...@gmail.com` on 1 Dec 2010 at 11:38

**Comment by GoogleCodeExporter** [comment]
```
I am able to reproduce it now. For some reason, a unicode file is getting 
converted by to bytestring and that is creating some issues. Please give me 
some time.
```

Original comment by `nitinbh...@gmail.com` on 1 Dec 2010 at 12:32

**Comment by GoogleCodeExporter** [comment]
```
I have added some additional checks for better unicode handling. Please try the 
trunk.
```

Original comment by `nitinbh...@gmail.com` on 1 Dec 2010 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
Using the latest trunk version, svnlog2sqlite survied the revision(s) in 
question without loggin any warning and crashed at a later revision due to a 
different problem.
```

Original comment by `G.Ohr...@web.de` on 2 Dec 2010 at 9:17

**Comment by GoogleCodeExporter** [comment]
```
I can confirm it's working for me now. Thanks!
```

Original comment by `sam.jan...@gmail.com` on 5 Dec 2010 at 4:43

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 6 Dec 2010 at 3:28
- Changed state: **Fixed**
