### ISSUE TITLE
Error while build sqlite-DB: "TypeError: expected a character buffer object"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#50]
```
What steps will reproduce the problem?
When I read that the ubiquitous "unknown node"-problem had been fixed, I 
thought I'd give svnplot another try - unfortunately to no avail. :-(

The problem occured while building the sqlite DB for our internal repository.

What is the expected output? What do you see instead?
"Found Error expected a character buffer object"

What version of the product are you using? On what operating system?
Snapshot r451 (2010-11-30)

Please provide any additional information below.

The offending path /XXX/YYY is a directory which seems to have been deleted in 
this revision, while its contents have been moved into another, new directory.

console:
********
Found Error Unknown node kind for 'file:///XXX/svnrepos_svn16/XXX/ZZZ22'
Trying again (1)
Found Error expected a character buffer object
Trying again (2)
Found Error expected a character buffer object
Trying again (3)


svnlog2sqlite.log:
******************

DEBUG Found file deletion for </XXX/YYY>
DEBUG Binary file check for file </XXX/YYY> revision:5493
DEBUG 5494 : /XXX/YYY : D : 0 : 0
DEBUG Number revisions converted : 1 (Rev no : 5494)
INFO Number revisions converted : 1 (Rev no : 5494)
ERROR Found Error expected a character buffer object
Traceback (most recent call last):
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlog2sqlite.py", line 56, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlog2sqlite.py", line 115, in ConvertRevs
    for revlog in svnloglist:
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 540, in next
    svnrevlog = SVNRevLog(self.logclient, revlog)
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 710, in __init__
    self.__updateCopyFromPaths()
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 756, in __updateCopyFromPaths
    change['copyfrom_path'] = curfilepath.replace(curpath, copyfrompath,1)
TypeError: expected a character buffer object
INFO Root url found : file:///XXX/svnrepos_svn16
DEBUG Trying to get head revision rooturl:file:///XXX/svnrepos_svn16
DEBUG Found head revision 26762
DEBUG Trying to get revision log. revno:1, url=file:///XXX/svnrepos_svn16
INFO Start-End Rev no : 1-26762
INFO Converting revisions 5495 to 26762
INFO Updating revision from 5495 to 26762
INFO updating logs 5495 to 26762
DEBUG Trying to get revision logs [5495:26762]
ERROR Found Error expected a character buffer object
Traceback (most recent call last):
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlog2sqlite.py", line 56, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlog2sqlite.py", line 115, in ConvertRevs
    for revlog in svnloglist:
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 540, in next
    svnrevlog = SVNRevLog(self.logclient, revlog)
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 710, in __init__
    self.__updateCopyFromPaths()
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 756, in __updateCopyFromPaths
    change['copyfrom_path'] = curfilepath.replace(curpath, copyfrompath,1)
TypeError: expected a character buffer object

```

Original issue reported on code.google.com by `G.Ohr...@web.de` on 30 Nov 2010 at 12:36

**Comment by GoogleCodeExporter** [comment]
```
Whoops, sorry, I created a dublicate bug report. I should have searched the 
existing reports more thoroughly before posting. :-(

Mh, how can I tag it as "dublicate" or "invalid"? (I'm new to the Google Code 
issuetracker.)
```

Original comment by `G.Ohr...@web.de` on 30 Nov 2010 at 12:40

**Comment by GoogleCodeExporter** [comment]
```
I will mark it as duplicate. 
```

Original comment by `nitinbh...@gmail.com` on 30 Nov 2010 at 12:47
- Changed state: **Duplicate**
