### ISSUE TITLE
"Unknown node kind"-crash again (still?)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#52]
```
What steps will reproduce the problem?
"python svnlog2sqlite.py -l -g file:///PATH/svnrepos_svn16/ 
c:\PATH\svnrepos_svn16_svnplot.sqlite"
run against our internal development repository.

What is the expected output? What do you see instead?
The data import crashes in revision 5500 with messages:
Logging to file c:\PATH\svnlog2sqlite.log
Found Error Unknown node kind for 
'file:///PATH/svnrepos_svn16/branches/releases/PROJECT/ZZZ/dirA'
Trying again (1)
Found Error Unknown node kind for 
'file:///PATH/svnrepos_svn16/branches/releases/PROJECT/AAA/dirB'
Trying again (2)
Found Error Unknown node kind for 
'file:///PATH/svnrepos_svn16/branches/releases/PROJECT/XXX/dirabc'
Trying again (3)

Although it looks as if the problems above would be related, in fact they are 
not - all "Found Error"s refer to different paths and different revisions in 
the repository, while the first two are not fatal but the third one is - is it 
possible that there's also a bug in the retry logic?

What version of the product are you using? On what operating system?
* 2010-12-01 snapshot on Windows XP
* svn 1.6.13-created repository, based on an imported svn-1.4-format repository.

Please provide any additional information below.

Path "/branches/releases/PROJECT/XXX/dirabc" was deleted in changeset 5495, its 
contents being moved into another, newly created directory within the branch.
The deletion of "/TRUNK/XXX/dirabc" mentioned in the first log line below seems 
to represent the merge of this deletion / content move operation from the 
branch to the trunk.

2010-12-01 21:33:10,012 DEBUG Found file deletion for </TRUNK/XXX/dirabc>
2010-12-01 21:33:10,012 DEBUG Binary file check for file 
</branches/releases/PROJECT/XXX/dirabc> revision:5495
2010-12-01 21:33:10,026 ERROR Found Error Unknown node kind for 
'file:///PATH/svnrepos_svn16/branches/releases/PROJECT/XXX/dirabc'
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 56, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 125, in ConvertRevs
    for change in revlog.getDiffLineCount(bUpdLineCount):
  File "C:\...\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 819, in getDiffLineCount
    change.updateDiffLineCountFromDict(diffCountDict)
  File "C:\...\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 668, in updateDiffLineCountFromDict
    if( diffCountDict!= None and not self.isBinaryFile() and diffCountDict.has_key(filename)):
  File "C:\...\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 658, in isBinaryFile
    binary = self.logclient.isBinaryFile(filepath, revno)
  File "C:\...\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 403, in isBinaryFile
    binary = self.__isBinaryFile(filepath, revno)
  File "C:\...\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 384, in __isBinaryFile
    proplist = self.svnclient.proplist(url, revision=rev)
ClientError: Unknown node kind for 
'file:///PATH/svnrepos_svn16/branches/releases/PROJECT/XXX/dirabc'

```

Original issue reported on code.google.com by `G.Ohr...@web.de` on 2 Dec 2010 at 9:15

**Comment by GoogleCodeExporter** [comment]
```
I think i have missed some condition in 'unknown node kind' issue. will check 
again.
```

Original comment by `nitinbh...@gmail.com` on 2 Dec 2010 at 10:23

**Comment by GoogleCodeExporter** [comment]
```
Please generate a verbose svn log message for the particular revision. Add the 
log details. It will give me information on 'add'/delete pattern and give me 
some clue what is happening.

I think you will need 'svn log -r <revno> -v'

```

Original comment by `nitinbh...@gmail.com` on 2 Dec 2010 at 12:43

**Comment by GoogleCodeExporter** [comment]
```
I fear I also cannot publically post the verbose log, although I could probably 
mail it to you personally. On the page linked from your developer's profile 
(https://code.google.com/u/nitinbhide/) I could only read something about the 
bible - we all do hate cybersquatters, right? ;) - but looking around a bit I 
found nitinbhide .oO(at) thinkingcraftsman <dot> in, will a mail to this 
address successfully reach you?
The affected revision seems to be r5500, will a log for this revision suffice?
```

Original comment by `G.Ohr...@web.de` on 2 Dec 2010 at 2:13

**Comment by GoogleCodeExporter** [comment]
```
>>will a log for this revision suffice?
I think so.
>> will a mail to this address successfully reach you
Yes.
```

Original comment by `nitinbh...@gmail.com` on 2 Dec 2010 at 2:47

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 2 Dec 2010 at 4:10
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Found the problem when directory is deleted while tagging/copying. Now fixed in 
trunk.
```

Original comment by `nitinbh...@gmail.com` on 2 Dec 2010 at 4:16
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
The import successfully passed the critical revisions and is still running. :)

BTW, the homepage link in your profile still points to the cybersquatted web 
site. (blogpsot.com)
```

Original comment by `G.Ohr...@web.de` on 6 Dec 2010 at 1:49

**Comment by GoogleCodeExporter** [comment]
```
fixed the homepage link. I think I made a spelling mistake while updating it 
last time.
```

Original comment by `nitinbh...@gmail.com` on 7 Dec 2010 at 4:08
