### ISSUE TITLE
Another unknown node error with strange extra "x"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#53]
```
Hi there,

SVNPlot is great!  I too am getting some unknown node errors.  When I look in 
the log its occurring at a place where the user had a Word 2007 document 
".docx" and then because some folks only had Office 2003 it was replaced with a 
Word 2003 ".doc".

So in the log below your code finds the ".docx" deletion and then goes to do a 
binary check on the file but then afterwards seems to call it ".docxx".  Any 
idea where that extra "x" is coming from?

Anyhow thanks for a nifty product and being so responsive to all these issues 
folks are reporting.

Cheers,

Paul

2010-12-03 13:15:56,325 DEBUG 20929 : 
/trunk/JOBS/RAD/Docs/tmdl_extract/tmdl_extract_procedures.doc : A : 0 : 0 
2010-12-03 13:15:56,325 DEBUG Found file deletion for 
</trunk/JOBS/RAD/Docs/tmdl_extract/tmdl_extract_procedures.docx>
2010-12-03 13:15:56,325 DEBUG Binary file check for file 
</trunk/JOBS/RAD/Docs/tmdl_extract/tmdl_extract_procedures.docxx> revision:20928
2010-12-03 13:15:56,434 ERROR Diff LIne error
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 674, in updateDiffLineCountFromDict
    if( diffCountDict!= None and filename in diffCountDict and not self.isBinaryFile()):
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 663, in isBinaryFile
    binary = self.logclient.isBinaryFile(filepath, revno)
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 403, in isBinaryFile
    binary = self.__isBinaryFile(filepath, revno)
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 384, in __isBinaryFile
    proplist = self.svnclient.proplist(url, revision=rev)
ClientError: Unknown node kind for 
'https://teamforge.induscorp.com/svn/repos/waters/trunk/JOBS/RAD/Docs/tmdl_extra
ct/tmdl_extract_procedures.docxx'
2010-12-03 13:15:56,528 ERROR Found Error Unknown node kind for 
'https://teamforge.induscorp.com/svn/repos/waters/trunk/JOBS/RAD/Docs/tmdl_extra
ct/tmdl_extract_procedures.docxx'
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\svnplot\svnlog2sqlite.py", line 56, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "C:\Python26\Lib\site-packages\svnplot\svnlog2sqlite.py", line 125, in ConvertRevs
    for change in revlog.getDiffLineCount(bUpdLineCount):
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 828, in getDiffLineCount
    change.updateDiffLineCountFromDict(diffCountDict)
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 674, in updateDiffLineCountFromDict
    if( diffCountDict!= None and filename in diffCountDict and not self.isBinaryFile()):
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 663, in isBinaryFile
    binary = self.logclient.isBinaryFile(filepath, revno)
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 403, in isBinaryFile
    binary = self.__isBinaryFile(filepath, revno)
  File "C:\Python26\Lib\site-packages\svnplot\svnlogiter.py", line 384, in __isBinaryFile
    proplist = self.svnclient.proplist(url, revision=rev)
ClientError: Unknown node kind for 
'https://teamforge.induscorp.com/svn/repos/waters/trunk/JOBS/RAD/Docs/tmdl_extra
ct/tmdl_extract_procedures.docxx'
```

Original issue reported on code.google.com by `pauldzie...@gmail.com` on 3 Dec 2010 at 8:20

**Comment by GoogleCodeExporter** [comment]
```
Extra 'x' is strange. which version of svnplot you are using ? if you are not 
using the latest version from trunk, can you check the latest trunk version. I 
have done some bug fixes for 'unknown node kind' error.
```

Original comment by `nitinbh...@gmail.com` on 4 Dec 2010 at 1:07

**Comment by GoogleCodeExporter** [comment]
```
I could not reproduce this error. Please check with latest release(0.7.3) and 
see if still face the problems.
```

Original comment by `nitinbh...@gmail.com` on 7 Jan 2011 at 4:34

**Comment by GoogleCodeExporter** [comment]
```
Hello,
Sorry I took so long to follow up on this.  I think it's possible the Unicode 
issues could be elsewhere in the Python stack or else some weird combination of 
factors.  I decided to start from scratch and installed the latest versions of 
Python, pysvn and svnplot on my home computer.  When I ran svnlog2sqlite 
everything went fine and in fact gave me great results!  No problems at all.  
Please close this ticket.  

Thanks so much!
Paul
```

Original comment by `pauldzie...@gmail.com` on 6 Feb 2011 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
Thanks.
```

Original comment by `nitinbh...@gmail.com` on 7 Feb 2011 at 4:31
- Changed state: **Verified**
