### ISSUE TITLE
Assertion failure during svnlog2sqlite-run

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#54]
```
What steps will reproduce the problem?
1. Converting a specific internal development repository using svnlog2sqlite.py

What is the expected output? What do you see instead?
The import fails with an assertion failure.
An Unicode-related error is printed to the console before, but I'm not sure it 
actually refers to the later crash.

I could not find any log entry related to this Unicode comparison failure.

What version of the product are you using? On what operating system?
Snapshot from 06.12.2010 on Windows XP.

Please provide any additional information below.

Console:
********
> python svnlog2sqlite.py -l -g file:///XDIS_IDE/svnrepos_svn16/ 
c:\XDIS_IDE\svnrepos_svn16_svnplot.sqlite
Updating the subversion log
Repository : file:///AAA/svnrepos_svn16/
Log database filepath : c:\AAA\svnrepos_svn16_svnplot.sqlite
Update Changed Line Count : True
Logging to file c:\AAA\svnlog2sqlite.log
C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py:712: 
UnicodeWarning: Unicode equal comparison failed to convert both arguments to 
Unicode - interpreting them as being unequal
  if(diffDict.has_key(filename) == True):
Found Error
Trying again (1)
Found Error
Trying again (2)
Found Error
Trying again (3)

Log:
****
2010-12-06 21:47:25,089 DEBUG 15842 : /XXX/pom.xml : M : 1 : 1
2010-12-06 21:47:25,089 DEBUG Number revisions converted : 15842 (Rev no : 
15842)
2010-12-06 21:47:25,089 INFO Number revisions converted : 15842 (Rev no : 15842)
2010-12-06 21:47:25,089 ERROR Found Error
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 56, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 115, in ConvertRevs
    for revlog in svnloglist:
  File "C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 550, in next
    svnrevlog = SVNRevLog(self.logclient, revlog)
  File "C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 732, in __init__
    self.__updateCopyFromPaths()
  File "C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 776, in __updateCopyFromPaths
    assert(change['copyfrom_path'] is None)
AssertionError
2010-12-06 21:47:25,184 INFO Root url found : file:///AAA/svnrepos_svn16
2010-12-06 21:47:25,184 DEBUG Trying to get head revision 
rooturl:file:///AAA/svnrepos_svn16
2010-12-06 21:47:25,198 DEBUG Found head revision 26762
2010-12-06 21:47:25,198 DEBUG Trying to get revision log. revno:1, 
url=file:///AAA/svnrepos_svn16
2010-12-06 21:47:25,214 INFO Start-End Rev no : 1-26762
2010-12-06 21:47:25,214 INFO Converting revisions 15843 to 26762
2010-12-06 21:47:25,214 INFO Updating revision from 15843 to 26762
2010-12-06 21:47:25,214 INFO updating logs 15843 to 26762
2010-12-06 21:47:25,214 DEBUG Trying to get revision logs [15843:26762]
2010-12-06 21:47:25,573 ERROR Found Error
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 56, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 115, in ConvertRevs
    for revlog in svnloglist:
  File "C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 550, in next
    svnrevlog = SVNRevLog(self.logclient, revlog)
  File "C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 732, in __init__
    self.__updateCopyFromPaths()
  File "C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 776, in __updateCopyFromPaths
    assert(change['copyfrom_path'] is None)
AssertionError
2010-12-06 21:47:25,573 INFO Root url found : file:///AAA/svnrepos_svn16
2010-12-06 21:47:25,573 DEBUG Trying to get head revision 
rooturl:file:///AAA/svnrepos_svn16
2010-12-06 21:47:25,573 DEBUG Found head revision 26762
2010-12-06 21:47:25,573 DEBUG Trying to get revision log. revno:1, 
url=file:///AAA/svnrepos_svn16
2010-12-06 21:47:25,589 INFO Start-End Rev no : 1-26762
2010-12-06 21:47:25,589 INFO Converting revisions 15843 to 26762
2010-12-06 21:47:25,589 INFO Updating revision from 15843 to 26762
2010-12-06 21:47:25,589 INFO updating logs 15843 to 26762
2010-12-06 21:47:25,589 DEBUG Trying to get revision logs [15843:26762]
2010-12-06 21:47:25,698 ERROR Found Error
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 56, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 115, in ConvertRevs
    for revlog in svnloglist:
  File "C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 550, in next
    svnrevlog = SVNRevLog(self.logclient, revlog)
  File "C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 732, in __init__
    self.__updateCopyFromPaths()
  File "C:\AAA\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 776, in __updateCopyFromPaths
    assert(change['copyfrom_path'] is None)
AssertionError

```

Original issue reported on code.google.com by `G.Ohr...@web.de` on 7 Dec 2010 at 9:58

**Comment by GoogleCodeExporter** [comment]
```
Looks like another unicode problem. I think with your help, i am going to fix 
all potential unicode problems in a few days. :-)

Please give me two days to look at it.
```

Original comment by `nitinbh...@gmail.com` on 7 Dec 2010 at 12:21

**Comment by GoogleCodeExporter** [comment]
```
Well, looks as if during the last few years we've collected all possible sorts 
of Unicode- and Move/Branch/Delete-related data constellations Subversion 
allows for... ;)
It's a pity that the repository is not public so it's not possible for you to 
test against it directly... :-(
At least the import now runs about half-way through our data before crashing, 
which is a significant improvement compared to any other version of svnplot 
I've ever tried. ;)
```

Original comment by `G.Ohr...@web.de` on 7 Dec 2010 at 12:31

**Comment by GoogleCodeExporter** [comment]
```
I have done some more unicode cleanup. Please check the trunk.
```

Original comment by `nitinbh...@gmail.com` on 7 Dec 2010 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
Ok, a new import is running...

I startet with a fresh import, deleting the partially generated SQLite-DB which 
already was 450 MB in size.
```

Original comment by `G.Ohr...@web.de` on 7 Dec 2010 at 4:38

**Comment by GoogleCodeExporter** [comment]
```
The import just (! ;-) failed with what looks like just the same exception at 
the same position.
```

Original comment by `G.Ohr...@web.de` on 8 Dec 2010 at 10:03

**Comment by GoogleCodeExporter** [comment]
```
Any ideas on how to go about this ?? Can you send me the log for failing 
version number ?

Also there is no need to do a 'fresh import' always. You can just delete rows 
after some particular version number and just svnlog2sqlite.py again. For 
example, if you want to regenerate the data after version number 550, then 
delete all rows where 'revno > 550' from SVNLog and SVNLogDetail tables.
```

Original comment by `nitinbh...@gmail.com` on 9 Dec 2010 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
from bug it looks at a 'deleted' file entry can also have 'copyfrom_path' 
entry. I have changed the assert to appropriate if check. Please check the 
trunk.

I suggest that you delete all the entries with 'revno' > 15840 from SVNLog and 
SVNLogDetail tables of the generated sqlite database. This way you don't have 
to run the 'whole' conversion again.
```

Original comment by `nitinbh...@gmail.com` on 9 Dec 2010 at 1:21

**Comment by GoogleCodeExporter** [comment]
```
You're faster in providing bug-fixes than I'm in providing debugging 
information... ;)
Import is running again, started at revision 15840 as suggested above. It 
successfully passed revision 15843, let's see how far it runs this time. :)
```

Original comment by `G.Ohr...@web.de` on 9 Dec 2010 at 2:02

**Comment by GoogleCodeExporter** [comment]
```
The python instance running svnplot was just aborted by Windows with an "Out of 
memory" error. Simply restarting it seems to work, though - could there be a 
memory leak in within svnplot, or is an increasing virtual memory image size 
during runtime to be expected?
Does svnplot use sqlite transactions for each revision, so a crash will cleanly 
roll back all work in progress, leaving a consistent state?
```

Original comment by `G.Ohr...@web.de` on 9 Dec 2010 at 4:11

**Comment by GoogleCodeExporter** [comment]
```
s/svnplot/svnlog2sqlite.py/g
```

Original comment by `G.Ohr...@web.de` on 9 Dec 2010 at 4:11

**Comment by GoogleCodeExporter** [comment]
```
I think there is a chance the out of memory error result in some error in the 
database. However, in my experience committing after every revision can be 
slow. One compromise is to commit after every 10 revisions. So if a crash 
occurs last 10 revisions are repeated in the next run.
```

Original comment by `nitinbh...@gmail.com` on 9 Dec 2010 at 6:13

**Comment by GoogleCodeExporter** [comment]
```
for long running processes I have seen a increasing virtual memory image size. 
I am not sure the problem is in svnplot or python-sqlite interface. 

```

Original comment by `nitinbh...@gmail.com` on 9 Dec 2010 at 6:16
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
There are two situations where you may get 'out of memory' error. 
1. Large number of files added in a single commit 
2. A single large file (>1 GB) added.

I will see how to address these.
```

Original comment by `nitinbh...@gmail.com` on 10 Dec 2010 at 3:33

**Comment by GoogleCodeExporter** [comment]
```
I have added some additional checks for addition/deletion. With this check for 
file additions/deletions individual file diff will be used for linecount rather 
than diff of entire revision. please check the code in trunk.
```

Original comment by `nitinbh...@gmail.com` on 10 Dec 2010 at 4:08

**Comment by GoogleCodeExporter** [comment]
```
Hi! I'm now trying the latest trunk version, but as I wrote, simply re-starting 
the run from where it left of also helped around the OOM-errors in the previous 
versions.

If restarted after crashing, svnlog2sqlite.py would happily continue to import 
revisions from where it left off, until running into the next OOM-error several 
thousand revisions later. (See my comment 9 
http://code.google.com/p/svnplot/issues/detail?id=54#c9) The crashed always 
seemed to happen when the virtual process size approched or exceeded 256 MB.

When I asked about the commit after every (N) revision(s) I just wanted to know 
if the import uses autocommit and thus could leave an inconsistently imported 
revision after crashing, or if it would ensure that the last revision in the 
database would be consistent after restarting by rolling back all partially / 
incompletely imported data. A regular commit after any number of revisions - 
more precisely: any commit strategy not performing any commits during the 
import of a given revision - would suffice to do so, and that's just what I 
wanted to know. :)
```

Original comment by `G.Ohr...@web.de` on 13 Dec 2010 at 9:07

**Comment by GoogleCodeExporter** [comment]
```
Concerning the OOM-error mentioned above: Maybe the process exceeds its allowed 
image size due to mmapped files? At least on POSIX systems sqlite does mmap 
certain data, however I'm not sure how such data is accounted for on Windows 
systems...
```

Original comment by `G.Ohr...@web.de` on 13 Dec 2010 at 11:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 30 Dec 2010 at 5:14

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 7 Jan 2011 at 4:33
- Changed state: **Fixed**
