### ISSUE TITLE
Unicode haunts you again...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#56]
```
What steps will reproduce the problem?
1. Import our now-famous repository using svnlog2sqlite.py

What is the expected output? What do you see instead?
The import seems to work flawlessly if you only look at the console, but 
hundreds of errors are hidden in the logs.

What version of the product are you using? On what operating system?
Snapshop from 2010-12-13

Please provide any additional information below.

Hundreds of the following errors get written to the logs, without 
svnlog2sqlite.py aborting or signalling anything to the controlling terminal:

2010-12-13 10:13:32,282 ERROR Error in diffline count
Traceback (most recent call last):
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 908, in __updateDiffCount
    diffcountdict[filename] = change.getDiffLineCount()
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 708, in getDiffLineCount
    diff_log = self.logclient.getRevFileDiff(filepath, revno,prev_filepath, prev_revno)
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 331, in getRevFileDiff
    diff_log = makeunicode(diff_log)
  File "C:\XXX\Python 2.6.5\Lib\site-packages\svnplot\svnlogiter.py", line 41, in makeunicode
    uns=unicode(s, encoding, errors)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 359-364: 
unsupported Unicode code range

C:\XXX>egrep " ERROR " svnlog2sqlite.log | wc -l
939
```

Original issue reported on code.google.com by `G.Ohr...@web.de` on 13 Dec 2010 at 5:13

**Comment by GoogleCodeExporter** [comment]
```
problem seems to be svn diff returns 'ascii output'. I tried to convert it in 
unicode. But that didn't work well. Hence I have to remove makeunicode() call 
from the diff functions for the time being. It will remove the errors from the 
diff log code. However, it will probably reappear some place else. I think I 
have to dig deep into the unicode handling of svn and then think of better fix. 
```

Original comment by `nitinbh...@gmail.com` on 14 Dec 2010 at 7:58
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Finally I was able reproduce the unicode issues. I added 'german wikipedia' 
page to repository and used that for testing. :-)

I think I have fixed this issues. Turned out to trickier and there still may be 
corner cases. If filename contains non-ascii characters then filename inside 
results return by 'svn diff' are slightly different than the filenames returned 
by svn log. I am not sure why. I have added work around for this situation.

however, I think for now you have regenerate the sqlite database again. Sorry 
about that. And Thanks for the patience.
```

Original comment by `nitinbh...@gmail.com` on 14 Dec 2010 at 7:56

**Comment by GoogleCodeExporter** [comment]
```
> If filename contains non-ascii characters then filename inside results return
> by 'svn diff' are slightly different than the filenames returned by svn log.

This sounds like a bug or at least a misfeature in subversion... Did you ask 
the svn dev about this?

I'll retry the import with a fresh DB using your latest trunk.
```

Original comment by `G.Ohr...@web.de` on 15 Dec 2010 at 7:43

**Comment by GoogleCodeExporter** [comment]
```
found that svn diff has 'header_encoding' parameter. Now I have set to 'utf-8'. 
However, to make sure that it works all non-ascii encodings you have to set 
'APR_ICONV_PATH' parameter to 'subversion command line client' iconv directory 
path.
```

Original comment by `nitinbh...@gmail.com` on 24 Dec 2010 at 12:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 30 Dec 2010 at 5:14

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 7 Jan 2011 at 4:33
- Changed state: **Fixed**
