### ISSUE TITLE
running svnplot without line numbers throws exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#59]
```
What steps will reproduce the problem?

Generate data base without line number info. Then run svnplot and it
fails adding attributes to graph that is None.

What is the expected output? What do you see instead?

rjh@rjhx201:~/Downloads/SVNPlot-0.7.2/build/lib.linux-x86_64-2.6/svnplot$ 
python ./svnplot.py /tmp/db GRAPHS
Traceback (most recent call last):
  File "./svnplot.py", line 636, in <module>
    RunMain()
  File "./svnplot.py", line 633, in RunMain
    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize, options.maxdircount)
  File "./svnplot.py", line 239, in AllGraphs
    self.DirectorySizeLineGraph(self._getGraphFileName(dirpath, "DirSizeLine"),self.dirdepth, maxdircount)
  File "./svnplot.py", line 485, in DirectorySizeLineGraph
    self._closeDateLineGraph(ax, filename)            
  File "/home/rjh/Downloads/SVNPlot-0.7.2/build/lib.linux-x86_64-2.6/svnplot/svnplotmatplotlib.py", line 198, in _closeDateLineGraph
    assert(ax != None)
AssertionError


What version of the product are you using? On what operating system?

0.7.2 on ubuntu lucid

Please provide any additional information below.

Acceptable fix seems to be at line 481 

        if ax:
            self._addFigureLegend(ax, dirlist, loc="center right", ncol=1)
            ax.set_title('Directory Size (Lines of Code)')
            ax.set_ylabel('Lines')
            self._closeDateLineGraph(ax, filename)          



```

Original issue reported on code.google.com by `rjharri...@gmail.com` on 24 Dec 2010 at 4:36

**Comment by GoogleCodeExporter** [comment]
```
Thanks I will add the fix to 'trunk' today.
```

Original comment by `nitinbh...@gmail.com` on 24 Dec 2010 at 5:34

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r466.
```

Original comment by `nitinbh...@gmail.com` on 24 Dec 2010 at 12:47
- Changed state: **Fixed**
