### ISSUE TITLE
svn client unable to open local url when running svnlog2sqlite

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#60]
```
What steps will reproduce the problem?
1. svn co http://svnplot.googlecode.com/svn/trunk/ /path/to/local-svnplot
2. svnlog2sqlite.py file:///path/to/local-svnplot /my/db.sqlite

What is the expected output? What do you see instead?
I'd expect a database populated.  But I get a stack trace instead:
{{{
ERROR:root:Found Error Unable to open an ra_local session to URL
Unable to open repository 'file:///path/to/svnplot
Traceback (most recent call last):
  File "svnplot/svnlog2sqlite.py", line 51, in convert
    rootUrl = self.svnclient.getRootUrl()
  File "/tmp/SVNPlot-0.7.2/svnplot/svnlogiter.py", line 488, in getRootUrl
    self.getRootUrl2()
  File "/tmp/SVNPlot-0.7.2/svnplot/svnlogiter.py", line 455, in getRootUrl2
    revlog = self.svnclient.log(possibleroot, limit=1,discover_changed_paths=True)
ClientError: Unable to open an ra_local session to URL
}}}
The same thing happens when I give /path/to/svnplog without a protocol.

What version of the product are you using? On what operating system?
svnplot 0.7.2 (I also tried the trunk version), Ubuntu, python 2.6.5

Please provide any additional information below.


```

Original issue reported on code.google.com by `adam%sch...@gtempaccount.com` on 30 Dec 2010 at 1:13

**Comment by GoogleCodeExporter** [comment]
```
I first refer to local-svnplot, then svnplot directory in my description.  It's 
just a typo, the directory I tried it with does exist.
```

Original comment by `adam%sch...@gtempaccount.com` on 30 Dec 2010 at 1:17

**Comment by GoogleCodeExporter** [comment]
```
SVNPlot doesnot require checked out working copy. It works directly with the 
repository. Hence ' svn co' step is unnecessary. 

Try

svnlog2sqlite.py http://svnplot.googlecode.com/svn/trunk/  /my/db.sqlite

```

Original comment by `nitinbh...@gmail.com` on 30 Dec 2010 at 4:30

**Comment by GoogleCodeExporter** [comment]
```
Yes, the documentation is clear enough about not needing to do a checkout 
first.  It works nicely with a remote repo (hm, it took me an hour).  But I 
wondered how it works being offline and whether having a local copy can improve 
its performance.
```

Original comment by `adam%sch...@gtempaccount.com` on 31 Dec 2010 at 2:18

**Comment by GoogleCodeExporter** [comment]
```
You need a copy of the entire repository locally. A local check out will not 
work. Try creating a local copy of repository with 'svnsync' command. 

For file system repository, you have to use file:// (or file:/// on windows) 
instead of http. For example

svnlog2sqlite.py file://path/to/repository/ /my/db.sqlite


```

Original comment by `nitinbh...@gmail.com` on 1 Jan 2011 at 6:59

**Comment by GoogleCodeExporter** [comment]
```
Info about svnsync is available at 
http://svnbook.red-bean.com/en/1.5/svn.ref.svnsync.html
```

Original comment by `nitinbh...@gmail.com` on 1 Jan 2011 at 7:00

**Comment by GoogleCodeExporter** [comment]
```
closing it as I think this a mistake while using the svnlog2sqlite.py and no 
code is required. please reopen if needed.
```

Original comment by `nitinbh...@gmail.com` on 7 Jan 2011 at 4:38
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
OK, thank you for your info.  You may want to add a line to the documentation 
about using svnplot with a synchronized local repo.
```

Original comment by `adam%sch...@gtempaccount.com` on 9 Jan 2011 at 4:06

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
>>You may want to add a line to the documentation about using svnplot with a
>>synchronized local repo.
I will add to readme. I have already added a wiki 
page(http://code.google.com/p/svnplot/wiki/WhySVNplotIsSlowInUpdatingDatabaseFor
FirstTime). Please have a look

```

Original comment by `nitinbh...@gmail.com` on 10 Jan 2011 at 4:11
