### ISSUE TITLE
Problems when calling svnlog2sqlite.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#75]
```
What steps will reproduce the problem?
1. Error when calling svnlog2sqlite.py :
>>> svnlog2sqlite.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'svnlog2sqlite' is not defined
>>> svnlog2sqlite.py --help
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'svnlog2sqlite' is not defined
>>>

2. Error when calling with the two parameters <svn url> and <path tosvnplot DB>:

>>> svnlog2sqlite.py http://alertsvn/AlertRep C:\Versioning\svnplotDB
  File "<stdin>", line 1
    svnlog2sqlite.py http://alertsvn/AlertRep C:\Versioning\svnplotDB
                        ^
SyntaxError: invalid syntax
>>>
3.


In Windows 7 I installed:

- http://www.python.org/ftp/python/2.7.2/python-2.7.2.msi
- 
http://pysvn.tigris.org/files/documents/1233/48847/py27-pysvn-svn1615-1.7.5-1360
.exe
- 
http://sunet.dl.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.0.1/m
atplotlib-1.0.1.win32-py2.7.exe
http://svnplot.googlecode.com/files/SVNPlot-0.7.5.win32.exe

What can be the problem ?

Thank you,

Alexandre Dias


```

Original issue reported on code.google.com by `alexandr...@gmail.com` on 8 Sep 2011 at 7:29

**Comment by GoogleCodeExporter** [comment]
```
svnlog2sqlite.py is not a directly executable file on windows. Either Python 
2.6 (or above) is not installed or .py file is not associated with 'python' 
executable.

Try
1. Find you where python installed. Usually  c:\Python27.
2. Add python executable path to 'PATH' environment.
3. Then on command prompt try 'python svnlog2sqlite.py --help'. Now you should 
get help printed.
```

Original comment by `nitinbh...@gmail.com` on 8 Sep 2011 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
are you trying with svnlog2sqlite.py in pythonwin window or python interactive 
shell ?

It probably will not work from inside the python interactive shell. 

Try it from windows command line as following command

'python svnlog2sqlite.py --help' see help is printed. 
```

Original comment by `nitinbh...@gmail.com` on 16 Jan 2012 at 2:46

**Comment by GoogleCodeExporter** [comment]
```
seems to be an installation path related issue. since no change is required, 
marking it as fixed.
```

Original comment by `nitinbh...@gmail.com` on 16 Nov 2013 at 2:47
- Changed state: **WontFix**
