### ISSUE TITLE
Errors in svnplot-js.py and svnplot.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#76]
```
In order to use svnplot.py I needed to install numpy. But as numpy only works 
with Python 2.6 I had to remove Phyton 2.7 and all the associated plug-ins.

So I installed the following

python-2.6.5.msi
py26-pysvn-svn1615-1.7.5-1360.exe
matplotlib-1.0.1.win32-py2.6.exe
numpy-1.6.1-win32-superpack-python2.6
SVNPlot-0.7.5.win32.exe

When I had Python 2.7 the script svnplot-js.py didn't have any problem and the 
script svnplot.py didn't execute due to numpy.

Now both have problems. I recreated the database from the subversion repo and 
didn't see any error message.

When I execute  svnplot.py the following appears:

C:\Program Files\Python26\Lib\site-packages\svnplot>python svnplot.py -n 
261_stable_database -v -s 
http://alertsvn/AlertRep/branches/pfh/V2.6.1/stable/database
 C:\Versioning\svnplotDB\2612_stable_database_Sep12.db C:\Versioning\svnplotDB\graphs\2612
Calculating subversion stat graphs
Subversion log database : C:\Versioning\svnplotDB\2612_stable_database_Sep12.db
Graphs will generated in : C:\Versioning\svnplotDB\graphs\2612
Repository Name : 261_stable_database
Search path inside repository : 
http://alertsvn/AlertRep/branches/pfh/V2.6.1/stable/database%
Graph thumbnail size : 100
Maximum dir count: 10
using default html template
Set the search path to 
http://alertsvn/AlertRep/branches/pfh/V2.6.1/stable/database
Calculating Activity by day of week graph
Calculating Activity by time of day graph
Calculating Author Activity graph
ERROR:root:AuthorActivityGraph: Author count is 0
Calculating Commit activity graph
ERROR:root:CommitActivityGraph: Author count is 0
Calculating Commit Activity Index by time of day graph
Calculating Author commits trend histogram graph
Calculating Daily commit count graph
Calculating LoC graph
Calculating LoC and Churn graph
Calculating Developer Contribution graph
Calculating Average File Size graph
Calculating File Count graph
Calculating File Types graph
Calculating current Directory size pie graph
Calculating Directory size line graph
Calculating current Directory File Count pie graph
Calculating tag cloud for log messages
Calculating Author Tag Cloud
Calculating Basic stats
Traceback (most recent call last):
  File "svnplot.py", line 648, in <module>
    RunMain()
  File "svnplot.py", line 645, in RunMain
    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize, options.m
axdircount)
  File "svnplot.py", line 242, in AllGraphs
    graphParamDict = self._getGraphParamDict( thumbsize)
  File "svnplot.py", line 561, in _getGraphParamDict
    graphParamDict["BasicStats"] = self.BasicStats(HTMLBasicStatsTmpl)
  File "C:\Program Files\Python26\Lib\site-packages\svnplot\svnplotbase.py", lin
e 91, in BasicStats
    basestats = self.svnstats.getBasicStats()
  File "C:\Program Files\Python26\Lib\site-packages\svnplot\svnstats.py", line 9
69, in getBasicStats
    stats['FirstRevDate'] = row[0]
TypeError: 'NoneType' object is unsubscriptable


and for svnplot-js.py

C:\Program Files\Python26\Lib\site-packages\svnplot>python svnplot-js.py -n 
261_stable_database -v -j -s 
http://alertsvn/AlertRep/branches/pfh/V2.6.1/stable/dat
abase  C:\Versioning\svnplotDB\2612_stable_database_Sep12.db 
C:\Versioning\svnplotDB\graphs\2612
Calculating subversion stat graphs
Subversion log database : C:\Versioning\svnplotDB\2612_stable_database_Sep12.db
Graphs will generated in : C:\Versioning\svnplotDB\graphs\2612
Repository Name : 261_stable_database
Search path inside repository : 
http://alertsvn/AlertRep/branches/pfh/V2.6.1/stable/database%
Graph thumbnail size : 200
Maximum dir count: 10
using default html template
Set the search path to http://alertsvn/AlertRep/branches/pfh/V2.6.1/stable/datab
ase
Calculating tag cloud for log messages
Calculating Author Tag Cloud
Calculating Basic stats
Traceback (most recent call last):
  File "svnplot-js.py", line 1026, in <module>
    RunMain()
  File "svnplot-js.py", line 1023, in RunMain
    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize, options.m
axdircount,copyjs=options.copyjs)
  File "svnplot-js.py", line 323, in AllGraphs
    graphParamDict = self._getGraphParamDict(thumbsize, maxdircount)
  File "svnplot-js.py", line 913, in _getGraphParamDict
    graphParamDict["BasicStats"] = self.BasicStats(HTMLBasicStatsTmpl)
  File "C:\Program Files\Python26\Lib\site-packages\svnplot\svnplotbase.py", lin
e 91, in BasicStats
    basestats = self.svnstats.getBasicStats()
  File "C:\Program Files\Python26\Lib\site-packages\svnplot\svnstats.py", line 9
69, in getBasicStats
    stats['FirstRevDate'] = row[0]
TypeError: 'NoneType' object is unsubscriptable


Any ideas ?
```

Original issue reported on code.google.com by `alexandr...@gmail.com` on 16 Sep 2011 at 1:59

**Comment by GoogleCodeExporter** [comment]
```
I think you are directly executing svnplot.py or svnplot-js.py. 

You have to execute svnlog2sqlite.py first. svnlog2sqlite.py will query the 
subversion repository and create a local sqlite3 database of svn log 
information. svnplot.py then uses the information from the local sqlite3 
database to generate graphs. You are getting the error because the local 
sqlite3 database is empty.

check http://code.google.com/p/svnplot/wiki/Introduction for details to two 
steps.
```

Original comment by `nitinbh...@gmail.com` on 19 Sep 2011 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
It was something related with the local sqlite3 database. I recreated it again 
and now all works fine.

Thanks !
```

Original comment by `alexandr...@gmail.com` on 22 Sep 2011 at 10:34

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 22 Sep 2011 at 11:36
- Changed state: **Done**
