### ISSUE TITLE
SVN Error Code 175002

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#78]
```
What steps will reproduce the problem?
1. c:\Python27\Lib\site-packages\svnplot>svnlog2sqlite.py -u myUser -p myPass 
-l https://127.0.0.1/products/trunk C:/SVN_trunk.db
2.
3.

What is the expected output? What do you see instead?

ERROR:root:Found Error
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\svnplot\svnlog2sqlite.py", line 52, in convert
    (startrevno, endrevno) = self.svnclient.findStartEndRev(svnrevstartdate, svnrevenddate)
  File "C:\Python27\Lib\site-packages\svnplot\svnlogclient.py", line 268, in findStartEndRev
    firstrev, headrev = self.getStartEndRevForRepo(startdate, enddate)
  File "C:\Python27\Lib\site-packages\svnplot\svnlogclient.py", line 252, in getStartEndRevForRepo
    headrev = self._getHeadRev(enddate)
  File "C:\Python27\Lib\site-packages\svnplot\svnlogclient.py", line 234, in _getHeadRev
    revision_start=headrev, revision_end=headrev, discover_changed_paths=False)
ClientError: ("OPTIONS of 'https://127.0.0.1/products': could not connect to 
server (https://127.0.0.1)", [("OPTIONS of '
https://127.0.0.1/products': could not connect to server (https://127.0.0.1)", 
175002)])
Found Error. Rolled back recent changes
Error type <class 'pysvn._pysvn_2_7.ClientError'>
ERROR:root:SVN Error Code 175002
ERROR:root:OPTIONS of 'https://127.0.0.1/products': could not connect to server 
(https://127.0.0.1)
SVN Error : OPTIONS of 'https://127.0.0.1/products': could not connect to 
server (https://127.0.0.1)


What version of the product are you using? On what operating system?
I am using Windows 7 with Python27 installed. I have the pysvn installed for 
SVN 1.6.12. My source repository is SVN 1.6.11.

Please provide any additional information below.
Could you give any advice what could be the problem.
Note - I have diagnosed network connection which in not the case here (my 
labSupport technicians checked them). Connection to server works all right.
```

Original issue reported on code.google.com by `blazej.k...@gmail.com` on 16 Jan 2012 at 10:16

**Comment by GoogleCodeExporter** [comment]
```
from the log it seems you are connecting to localhost (i.e. 127.0.0.1). Is your 
repository hosted on your own machine ? Please check what the servername/ip of 
your repository.

As a quick check try the following.
svnlog2sqlite.py -l http://svnplot.googlecode.com/svn/trunk/ C:/SVNplot_trunk.db

This will create a sqlite database of svnplot repository. If this works, then 

Enter your repoistory url in the browser and see if you can access the 
repository. It should show you a directory listing of the files in the 
repository.
```

Original comment by `nitinbh...@gmail.com` on 16 Jan 2012 at 2:44
