### ISSUE TITLE
python svnlog2sqlite.py --help results in ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#79]
```
What steps will reproduce the problem?
1. 64 bit Win 7.
2. Installed python 2.7.2 64 bit, py27-pysvn-svn1615-1.7.5-1360, 
numpy-1.6.1-win32-superpack-python2.7, matplotlib-1.1.0.win-amd64-py2.7, 
basemap-1.0.2.win32-py2.7, SVNPlot-0.7.6.win32.
3. Note that pysvn, numpy, basemap and svnplot seems to be 32 bit.
4. Running python svnlog2sqlite.py -- help results in:

C:\Python27\Lib\site-packages\svnplot>python svnlog2sqlite.py --help
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 22, in <module>
    import svnlogiter
  File "C:\Python27\Lib\site-packages\svnplot\svnlogiter.py", line 24, in <modul
e>
    from svnlogclient import *
  File "C:\Python27\Lib\site-packages\svnplot\svnlogclient.py", line 23, in <mod
ule>
    import pysvn
  File "C:\Python27\lib\site-packages\pysvn\__init__.py", line 99, in <module>
    import _pysvn_2_7
ImportError: DLL load failed: %1 is not a valid Win32 application.

What is the expected output? What do you see instead?
No errors; ImportError: DLL load failed: %1 is not a valid Win32 application.

What version of the product are you using? On what operating system?
svnplot-0.7.6 on Win 7 64 bit.

Please provide any additional information below.

Installed python 2.7.2 64 bit, py27-pysvn-svn1615-1.7.5-1360, 
numpy-1.6.1-win32-superpack-python2.7, matplotlib-1.1.0.win-amd64-py2.7, 
basemap-1.0.2.win32-py2.7, SVNPlot-0.7.6.win32.

Note that pysvn, numpy, basemap and svnplot seems to be 32 bit.
```

Original issue reported on code.google.com by `gj9...@gmail.com` on 19 Jan 2012 at 9:38

**Comment by GoogleCodeExporter** [comment]
```
svnplot code itself is pure python. Hence will work with 64 bit or 32 bit. 

However svnlog2sqlite.py requires pysvn and that contains subversion binaries 
(dll). A 64 bit python cannot load 32 bit dlls. Pysvn windows installers 
contain 32 windows dlls. Hence doesnot work with 64 bit python.

Please install 32 bit python and 32 bit version of python modules or compile 
pysvn to get 64 bit binaries.

I will check if 64 bit pysvn binaries are available. 
```

Original comment by `nitinbh...@gmail.com` on 20 Jan 2012 at 10:30
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the quick response. That worked. I had tried with 32 bit python 
before unsuccessfully. I am assuming I had modules with mixed bit. Went ahead 
and removed python and all modules and re-installed 32 bit python and all 
modules with 32 bit this time and got the svnlog2sqlite --help show up 
correctly. Excited to look at svnplot in the coming days. Thanks again.
```

Original comment by `gj9...@gmail.com` on 21 Jan 2012 at 4:03
