### ISSUE TITLE
svnlog2sqlite gives up if file is missing from revision

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#8]
```
What steps will reproduce the problem?
1. run svnlog2sqlite to extract data

What is the expected output? What do you see instead?

should finish, but instead, in my case, fails:

Traceback (most recent call last):
  File "svnlog2sqlite.py", line 42, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 87, in ConvertRevs
    addedfiles, changedfiles, deletedfiles = revlog.changedFileCount(bChkIfDir)
  File "/home/bkc/src/SVNPlot-0.5.5/svnplot/svnlogiter.py", line 415, in
changedFileCount
    isdir = self.isDirectory(change)
  File "/home/bkc/src/SVNPlot-0.5.5/svnplot/svnlogiter.py", line 435, in
isDirectory
    isDir = self.logclient.isDirectory(revno, path, action)
  File "/home/bkc/src/SVNPlot-0.5.5/svnplot/svnlogiter.py", line 274, in
isDirectory
    entry = self.getInfo(changepath, revno)
  File "/home/bkc/src/SVNPlot-0.5.5/svnplot/svnlogiter.py", line 223, in
getInfo
    entry_list = self.svnclient.info2( url,revision=rev,recurse=False)
ClientError: URL
'http://svn.strader-ferris.com:3080/svn/trunk/trunk/Python/MurkWorks/scripts/CCX
LoadSICCodes.py'
non-existent in revision 624
Trying again (3)


What version of the product are you using? On what operating system?

0.5.5 on Ubuntu intrepid with system python 2.6

Please provide any additional information below.

This repository contains, perhaps 800 files and 8900 revs.

right now I am going to try changing ConvertRevs to skip an svn rev if an
exception is raised, not pretty but hopefully a missing rev won't break
plot generation.

```

Original issue reported on code.google.com by `bkcleme...@gmail.com` on 21 Jun 2009 at 8:59

**Comment by GoogleCodeExporter** [comment]
```
>>right now I am going to try changing ConvertRevs to skip an svn rev if an
>>exception is raised
It won't impact the graph generation.

i will try to fix the bug in next 2/3 days.
```

Original comment by `nitinbh...@gmail.com` on 22 Jun 2009 at 2:16

**Comment by GoogleCodeExporter** [comment]
```
I modified ConvertRevs to 'continue' whenever revlog.changedFileCount raises an
exception.. continue up to 1000 times.

But it seems that doesn't really help because I just keep getting additional 
errors
on different files in the same rev, or the same file in different revs and 
eventually
event 1000 'skips' is not enough.

I got to thinking that maybe the repository on this server is really corrupt in 
some way.

So I've tried another repository, running a newer subversion with only 780 revs 
and
maybe 150 files.

And darn, I start getting the same error:

like this (one of 100's):

error: URL
'https://svn.someplace.com:6380/svn/projects/projects/byways/trunk/production/we
b_data/xsl/content-templates/plan-your-stay.html'
non-existent in revision 385

looking at svn log for this file, I can see it was modified in rev 386 and 358.

on another file, it complains about rev 391, but subversion shows it *was* 
modified
in rev 391 (and 377 and 409).

So I am beginning to think maybe there's nothing wrong with the first 
repository.
Perhaps pysvn is not working correctly?

I am using ubuntu 8.10 and I installed pysvn from 
http://launchpadlibrarian.net/16433102/python-svn_1.6.0-1_amd64.deb


or maybe it doesn't like https protocol?  I'd really like to try this, I just 
can't
see what is going wrong.



```

Original comment by `bkcleme...@gmail.com` on 22 Jun 2009 at 3:12

**Comment by GoogleCodeExporter** [comment]
```
can you add the exact command used in this bugs comments (e.g. svnlog2sqlite 
<list of parameters>'). It will help me in tracking and reproducing the problem.
```

Original comment by `nitinbh...@gmail.com` on 22 Jun 2009 at 5:20

**Comment by GoogleCodeExporter** [comment]
```
Try the following 
(a) DONOT specify '-l' flag while using svnlog2sqlite.py. See if this throws 
any errors while conversion.
(b) Removing -l flag will not generate 'line count' data. All other graphs will 
be generated.


```

Original comment by `nitinbh...@gmail.com` on 22 Jun 2009 at 8:11

**Comment by GoogleCodeExporter** [comment]
```
Fixed the exception problem. Please get the current version of svnlogiter.py. 
(Download svnlogiter.py from 
http://code.google.com/p/svnplot/source/browse/trunk/src/svnplot/svnlogiter.py
and replace old file with the downloaded one.)

Please confirm if this fixes the bug. I will prepare a new release after the 
confirmation.
```

Original comment by `nitinbh...@gmail.com` on 22 Jun 2009 at 9:04

**Comment by GoogleCodeExporter** [comment]
```
When I process the smaller of the two repositories using:

python svnlog2sqlite.py https://svn.comeplace.com:6380/svn/projects/byways/trunk
~/svnplot.db

The program runs to completion. With -l it fails.

I really want the line count data.. but I hope this is a clue.

thanks

```

Original comment by `bkcleme...@gmail.com` on 22 Jun 2009 at 12:35

**Comment by GoogleCodeExporter** [comment]
```
Traceback:

ERROR:root:Error global name 'ClientError' is not defined
Error global name 'ClientError' is not defined
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 42, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount, maxtrycount)
  File "svnlog2sqlite.py", line 87, in ConvertRevs
    addedfiles, changedfiles, deletedfiles = revlog.changedFileCount(bChkIfDir)
  File "/home/bkc/src/svnplot-read-only/src/svnplot/svnlogiter.py", line 422, in
changedFileCount
    isdir = self.isDirectory(change)
  File "/home/bkc/src/svnplot-read-only/src/svnplot/svnlogiter.py", line 442, in
isDirectory
    isDir = self.logclient.isDirectory(revno, path, action)
  File "/home/bkc/src/svnplot-read-only/src/svnplot/svnlogiter.py", line 281, in
isDirectory
    except ClientError, expinst:
NameError: global name 'ClientError' is not defined
Trying again (1)

```

Original comment by `bkcleme...@gmail.com` on 22 Jun 2009 at 12:50

**Comment by GoogleCodeExporter** [comment]
```
restarting after applying:

Index: svnlogiter.py
===================================================================
--- svnlogiter.py   (revision 185)
+++ svnlogiter.py   (working copy)
@@ -27,6 +27,8 @@
 import types
 import tempfile

+from pysvn import ClientError
+

```

Original comment by `bkcleme...@gmail.com` on 22 Jun 2009 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
thanks for the patch. I have done the necessary modifications and committed new 
version of svnlogiter.py. Please confirm if this fixes the problem.
```

Original comment by `nitinbh...@gmail.com` on 22 Jun 2009 at 5:58

**Comment by GoogleCodeExporter** [comment]
```
After 9 hours of runtime, svnlog2sqlite completed.

But I get a different error now trying to create a graph. I'll open a new issue 
for
that, this issue I think can be closed.
```

Original comment by `bkcleme...@gmail.com` on 23 Jun 2009 at 2:21

**Comment by GoogleCodeExporter** [comment]
```
I got svnplot.py to create a graph after upgrading matplotlib.

however all the lines of code counts are 0, even though I used the -l option to
svnlog2sqlite.py

what could be wrong? 

```

Original comment by `bkcleme...@gmail.com` on 23 Jun 2009 at 2:42

**Comment by GoogleCodeExporter** [comment]
```
Not sure. If it has taken 9 hrs, then usually line count data should get 
updated (since typically geting line count data takes much more time). Since 
each line count calculation will require at least one http to svn server.

what is the number  of revisions in the repository ? 

Can you try it with a smaller repository (may be something on google code) and 
see if generates Line count graphs ?



```

Original comment by `nitinbh...@gmail.com` on 23 Jun 2009 at 3:29

**Comment by GoogleCodeExporter** [comment]
```
In the 'big' repository, there are 8900 revs.

I just tried it in a small repository, 780 revs.. 

same problem:

Head Revision Number    :   783
First Revision Number   :   3
Last Commit Date    :   Jun 16, 2009 04:02 PM
First Commit Date   :   Jul 30, 2008 06:53 PM
Revision Count  :   698
Author Count    :   3
File Count  :   960
LoC :   0

also the graph of file count (filecount.png) seems way off, it shows about 
280000
files, even though 960 seems to be correct.

and the graph showing count by file type is also correct.

```

Original comment by `bkcleme...@gmail.com` on 23 Jun 2009 at 3:54

**Comment by GoogleCodeExporter** [comment]
```
1. try "svnlog2sqlite.py -l <repository root path> <sqlitedbpath>". 
It seems you are using path upto 'trunk'. Previously svnplot worked on the 
'root path' only. Using any path inside the repository is recently added 
feature and it may have some issues.

 >>>the graph of file count (filecount.png)seems way off, it shows about 280000
>>>files, even though 960 seems to be correct.
There seems to be some error in the sql used to generate the filecount graphs. 
I will check again.



```

Original comment by `nitinbh...@gmail.com` on 23 Jun 2009 at 6:14

**Comment by GoogleCodeExporter** [comment]
```
svnlog2sqlite.py -l works when selecting the very root of the repository.


```

Original comment by `bkcleme...@gmail.com` on 24 Jun 2009 at 2:49

**Comment by GoogleCodeExporter** [comment]
```
sorry, let me clarify that previous comment. LOC is no-longer 0 when selecting 
the
root of the repository.
```

Original comment by `bkcleme...@gmail.com` on 24 Jun 2009 at 2:49

**Comment by GoogleCodeExporter** [comment]
```
Thanks. It will help me in narrowing down to the problem. 

Any ideas/suggestions on the graphs/report generated.
```

Original comment by `nitinbh...@gmail.com` on 25 Jun 2009 at 2:04

**Comment by GoogleCodeExporter** [comment]
```
I have  two thoughts on the graphs:

1. I'd like to just print the report from my browser into a pdf and email it to 
team
members. But the graphs are too small. I'd just make the graphs full size and 
not
bother with thumbnails and links.

2. If you used the google chart API, I wouldn't have to install matplotlib, 
which was
a pain on my older ubuntu. (apt-get install didn't work, it was too old, how to
download source).


```

Original comment by `bkcleme...@gmail.com` on 25 Jun 2009 at 2:07

**Comment by GoogleCodeExporter** [comment]
```
For Point 1: Just edit the HTML template defined at the top of svnplot.py. The 
thumbnails may still get generated on the server side. But the users need to 
not see them. I can add an option to enable/disable use of 'thumbnails'.

For Point 2 : It is possible. Only matplotlib dependency is in 
svnplot.py/svplotbase.py. svnstats.py is where the actual statistics generated. 
So i can add another file (e.g. svnplog-google.py) to use the google plot api.

Thanks for suggestions. 

May I request you to add these two suggestions as separate issue/enhancement 
requests to tracker ?
```

Original comment by `nitinbh...@gmail.com` on 25 Jun 2009 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
I think I finally fixed the linecount not getting updated for 'non-root' 
repositories. Requesting you to confirm the bug fix in the latest code in the 
trunk. 
```

Original comment by `nitinbh...@gmail.com` on 31 Aug 2009 at 4:56
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `nitinbh...@gmail.com` on 4 Feb 2010 at 5:16
- Changed state: **Fixed**
