### ISSUE TITLE
Error getting linecount for symlinks in repository

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#82]
```
What steps will reproduce the problem?
1. create a symlink in your project and commit
2. use svnlog2sqlite.py -l on project

What is the expected output? What do you see instead?
Expected is that project data is added to sqlite database.
What happens is an IOError.

What version of the product are you using? On what operating system?
version 0.7.6 on Debian Linux

Please provide any additional information below.

Attached is a patch that fixes the problem for me, as well as the debug log.

Original error:

ERROR:root:Error in diffline count
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/svnplot/svnlogiter.py", line 507, in __updateDiffCount
    diffcountdict[filename] = change.getDiffLineCount()
  File "/usr/local/lib/python2.6/dist-packages/svnplot/svnlogiter.py", line 244, in getDiffLineCount
    added = self.logclient.getLineCount(filepath, revno)
  File "/usr/local/lib/python2.6/dist-packages/svnplot/svnlogclient.py", line 539, in getLineCount
    linecount = self._getLineCount(filepath, revno)
  File "/usr/local/lib/python2.6/dist-packages/svnplot/svnlogclient.py", line 529, in _getLineCount
    with open(outpath,'r') as f:
IOError: [Errno 2] No such file or directory: '/tmp/svnplNGH6ED'
ERROR:root:Found Error
Traceback (most recent call last):
  File "svnlog2sqlite.py", line 55, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount)
  File "svnlog2sqlite.py", line 142, in ConvertRevs
    for change in revlog.getDiffLineCount(bUpdLineCount):
  File "/usr/local/lib/python2.6/dist-packages/svnplot/svnlogiter.py", line 402, in getDiffLineCount
    diffCountDict = self.__updateDiffCount()
  File "/usr/local/lib/python2.6/dist-packages/svnplot/svnlogiter.py", line 507, in __updateDiffCount
    diffcountdict[filename] = change.getDiffLineCount()
  File "/usr/local/lib/python2.6/dist-packages/svnplot/svnlogiter.py", line 244, in getDiffLineCount
    added = self.logclient.getLineCount(filepath, revno)
  File "/usr/local/lib/python2.6/dist-packages/svnplot/svnlogclient.py", line 539, in getLineCount
    linecount = self._getLineCount(filepath, revno)
  File "/usr/local/lib/python2.6/dist-packages/svnplot/svnlogclient.py", line 529, in _getLineCount
    with open(outpath,'r') as f:
IOError: [Errno 2] No such file or directory: '/tmp/svnplNGH6ED'
Found Error. Rolled back recent changes
Error type <type 'exceptions.IOError'>
Trying again (1)
```

Original issue reported on code.google.com by `EmTeedee...@gmail.com` on 1 Feb 2012 at 11:01

Attachments:
- [svnlogclient.patch](https://storage.googleapis.com/google-code-attachments/svnplot/issue-82/comment-0/svnlogclient.patch)
- [svnlog2sqlite.log](https://storage.googleapis.com/google-code-attachments/svnplot/issue-82/comment-0/svnlog2sqlite.log)

**Comment by GoogleCodeExporter** [comment]
```
thanks for the report. So far I never encountered a repository with symlinks. 
hence linecount on symlinks is completely untested. 

I will check patch.
```

Original comment by `nitinbh...@gmail.com` on 1 Feb 2012 at 2:42
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r541.
```

Original comment by `nitinbh...@gmail.com` on 1 Feb 2012 at 2:49
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
patch committed. Will be available in next release. 
```

Original comment by `nitinbh...@gmail.com` on 1 Feb 2012 at 2:49
