### ISSUE TITLE
AssertionError assert(len(dates) == len(fclist))

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#84]
```
What steps will reproduce the problem?
1. With the attached DB use the command  
python svnplot-js.py -n 'P:ER' sqlite.db hmtlOutput


What is the expected output? What do you see instead?

The following error message shows and no output was generated:

Traceback (most recent call last):
  File "svnplot-js.py", line 1026, in <module>
    RunMain()
  File "svnplot-js.py", line 1023, in RunMain
    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize, options.maxdircount,copyjs=options.copyjs)
  File "svnplot-js.py", line 323, in AllGraphs
    graphParamDict = self._getGraphParamDict(thumbsize, maxdircount)
  File "svnplot-js.py", line 919, in _getGraphParamDict
    graphParamDict["FileCountTable"] = self.FileCountGraph()
  File "svnplot-js.py", line 618, in FileCountGraph
    assert(len(dates) == len(fclist))
AssertionError

I think the issue is in the db file, but I cannot find it.


What version of the product are you using? On what operating system?
I am using Ubuntu 12.04 64bit and svnplot 0.7.6


```

Original issue reported on code.google.com by `sandra.u...@gmail.com` on 9 Jun 2012 at 11:53

Attachments:
- [sqlite](https://storage.googleapis.com/google-code-attachments/svnplot/issue-84/comment-0/sqlite)

**Comment by GoogleCodeExporter** [comment]
```
There was a issue in 0.7.6 which triggered these kinds of assertions. It is 
fixed in 0.7.7. 

However, there was another issue in svnplot-js.py in 0.7.7. It is now fixed in 
trunk and I could generate the graphs for attached data file. The fixes will be 
available in next release.
```

Original comment by `nitinbh...@gmail.com` on 4 Aug 2012 at 12:43
- Changed state: **Fixed**
