### ISSUE TITLE
Memory Error with big repository

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#85]
```
What steps will reproduce the problem?
1. Every times I generate data base with a big repository (2.5 Go)
2.
3.

What is the expected output? What do you see instead?




C:\Users\admusda>C:\Integration\python2.7\Lib\site-packages\svnplot\svnlog2sqlit
e.py -l http://svn/svn/mpai C:\mpai.db
Updating the subversion log
Repository : http://svn/svn/mpai/
SVN Log database filepath : C:\mpai.db
Extract Changed Line Count : True
C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py:527: 
RuntimeWarning: tempnam is a potential security risk to your program
  outpath = os.tempnam(self.tmppath, 'svnplot')
ERROR:root:Error in diffline count
Traceback (most recent call last):
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogiter.py", line 516, in __updateDiffCount
    diffcountdict = getDiffLineCountDict(revdiff_log)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 60, in getDiffLineCountDict
    diff_log = makeunicode(diff_log)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 41, in makeunicode
    uns=unicode(s, encoding, errors)
MemoryError
ERROR:root:Found Error
Traceback (most recent call last):
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlog2sqlite.py", line 55, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlog2sqlite.py", line 142, in ConvertRevs
    for change in revlog.getDiffLineCount(bUpdLineCount):
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogiter.py", line 402, in getDiffLineCount
    diffCountDict = self.__updateDiffCount()
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogiter.py", line 516, in __updateDiffCount
    diffcountdict = getDiffLineCountDict(revdiff_log)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 60, in getDiffLineCountDict
    diff_log = makeunicode(diff_log)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 41, in makeunicode
    uns=unicode(s, encoding, errors)
MemoryError
Found Error. Rolled back recent changes
Error type <type 'exceptions.MemoryError'>
Trying again (1)
ERROR:root:Error in diffline count
Traceback (most recent call last):
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogiter.py", line 515, in __updateDiffCount
    revdiff_log = self.logclient.getRevDiff(revno)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 351, in getRevDiff
    header_encoding=SVN_HEADER_ENCODING, diff_deleted=True)
MemoryError
ERROR:root:Found Error
Traceback (most recent call last):
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlog2sqlite.py", line 55, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlog2sqlite.py", line 142, in ConvertRevs
    for change in revlog.getDiffLineCount(bUpdLineCount):
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogiter.py", line 402, in getDiffLineCount
    diffCountDict = self.__updateDiffCount()
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogiter.py", line 515, in __updateDiffCount
    revdiff_log = self.logclient.getRevDiff(revno)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 351, in getRevDiff
    header_encoding=SVN_HEADER_ENCODING, diff_deleted=True)
MemoryError
Found Error. Rolled back recent changes
Error type <type 'exceptions.MemoryError'>
Trying again (2)
ERROR:root:Error in diffline count
Traceback (most recent call last):
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogiter.py", line 516, in __updateDiffCount
    diffcountdict = getDiffLineCountDict(revdiff_log)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 60, in getDiffLineCountDict
    diff_log = makeunicode(diff_log)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 41, in makeunicode
    uns=unicode(s, encoding, errors)
MemoryError
ERROR:root:Found Error
Traceback (most recent call last):
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlog2sqlite.py", line 55, in convert
    self.ConvertRevs(startrevno, endrevno, bUpdLineCount)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlog2sqlite.py", line 142, in ConvertRevs
    for change in revlog.getDiffLineCount(bUpdLineCount):
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogiter.py", line 402, in getDiffLineCount
    diffCountDict = self.__updateDiffCount()
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogiter.py", line 516, in __updateDiffCount
    diffcountdict = getDiffLineCountDict(revdiff_log)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 60, in getDiffLineCountDict
    diff_log = makeunicode(diff_log)
  File "C:\Integration\python2.7\Lib\site-packages\svnplot\svnlogclient.py", line 41, in makeunicode
    uns=unicode(s, encoding, errors)
MemoryError
Found Error. Rolled back recent changes
Error type <type 'exceptions.MemoryError'>
Trying again (3)




What version of the product are you using? On what operating system?

version of svnplot : 0.7.7
OS : Windows 2008 server

Please provide any additional information below.

Thanks for your help


```

Original issue reported on code.google.com by `aducou...@epsi.fr` on 3 Aug 2012 at 8:44

**Comment by GoogleCodeExporter** [comment]
```
Large repositories you will encounter this error because of two reasons

1. single commit contains many files or really large files. Then calculating 
line count causes problems. I done some fixes in the latest release to reduce 
the incidences of this error.

2. There are memory leaks in svn python client. So each revision causes a some 
memory leak and converting large number of revisions causes memory error. In 
such cases, just exit and restart svnlog2sqlite.py with the same db file. 
svnlog2sqlite.py checks how many revisions are already converted and start from 
that revision onwards.



```

Original comment by `nitinbh...@gmail.com` on 4 Aug 2012 at 7:16

**Comment by GoogleCodeExporter** [comment]
```
I try your solution 4 times but I have always the same problem with the same 
error.

Do you know an other possibility to generate graphs ?
```

Original comment by `aducou...@epsi.fr` on 6 Aug 2012 at 12:09

**Comment by GoogleCodeExporter** [comment]
```
It seems some binary file is being treated text file and causing 'diff' so big 
that unicode conversion is causing memory errors. This happens if the binary 
file any mime type defined in the svn properties. 

See if you have any large binary files in repository. Make sure that extensions 
of these files are defined in the BINARYFILEXT definition in svnlog2sqlite.py. 
If not, add the extension to BINARYFILEXT definition. svnlog2sqlite.py will 
ignore these files for linecount computation and conversion will proceed.

Hope this helps.

```

Original comment by `nitinbh...@gmail.com` on 6 Aug 2012 at 5:10

**Comment by GoogleCodeExporter** [comment]
```
So I have added all extensions of all big binary files in the BINARYFILEXT but 
I always have the same problem. 
Have you a way to know what binary file generate this error (maybe in log or in 
the db-journal) ?

Thank you for your help :)
```

Original comment by `aducou...@epsi.fr` on 8 Aug 2012 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
Have you enabled logging while executing svnlog2sqlite.py (-g or --log) option. 
It will create a log file. The revision number that is being processed in 
logged in the log file. 

Also try un-commenting following line (line no 495 in svnlogiter.py in function 
__useFileRevDiff).

#usefilerevdiff=True

It will force svnlog2sqlite to use file level diff. The log file will then 
contain the filename for which diff is being calculated.
```

Original comment by `nitinbh...@gmail.com` on 11 Aug 2012 at 12:11

**Comment by GoogleCodeExporter** [comment]
```
I don't understand why but vhen I execute svnlog2sqlite.py  with "-g" I have no 
more ERROR in my logs or in the console ...
It's perfect and my line count graphs are great, so no problem anymore.

If you have an explanation, I whish to understand the reason.

Thank you very much for your help. 
```

Original comment by `aducou...@epsi.fr` on 13 Aug 2012 at 1:22

**Comment by GoogleCodeExporter** [comment]
```
I have added a flag in the svnlog2sqlite.py for using the diff for per file per 
revision (--filediff).
```

Original comment by `nitinbh...@gmail.com` on 16 Nov 2013 at 2:45
- Changed state: **Fixed**
