### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waterxi/svnplot#96]
```
Traceback (most recent call last):
  File "/usr/bin/svnplotjs.py", line 13, in <module>
    RunMain()
  File "/usr/share/Python-2.7.2/lib/python2.7/site-packages/svnplot/svnplotjs.py", line 1322, in RunMain
    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize, options.maxdircount,copyjs=options.copyjs)
  File "/usr/share/Python-2.7.2/lib/python2.7/site-packages/svnplot/svnplotjs.py", line 447, in AllGraphs
    graphParamDict = self._getGraphParamDict(thumbsize, maxdircount,recentMonths )
  File "/usr/share/Python-2.7.2/lib/python2.7/site-packages/svnplot/svnplotjs.py", line 1184, in _getGraphParamDict
    graphParamDict["TagCloud"] = self.TagCloud()
  File "/usr/share/Python-2.7.2/lib/python2.7/site-packages/svnplot/svnplotbase.py", line 163, in TagCloud
    tagData = [{ 'text':str(x), 'count':freq} for x, freq in tagWordList]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 
3: ordinal not in range(128)
...
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4: 
ordinal not in range(128)
...

I don't know if it is relevant but I normaly always have to start svn with  
LC_CTYPE=pl_PL.UTF-8 Perhaps python binding isint started this way by your 
script?
```

Original issue reported on code.google.com by `adam...@gmail.com` on 5 Dec 2014 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
Thanks. I think you are right about the bindings parameter. I will check and 
fix this.
```

Original comment by `nitinbh...@gmail.com` on 6 Dec 2014 at 2:04
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
C:\Python27\lib\site-packages\matplotlib\pyplot.py:424: RuntimeWarning: More tha
n 20 figures have been opened. Figures created through the pyplot interface (`ma
tplotlib.pyplot.figure`) are retained until explicitly closed and may consume to
o much memory. (To control this warning, see the rcParam `figure.max_open_warnin
g`).
  max_open_warning, RuntimeWarning)
Calculating tag cloud for log messages
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\svnplot\svnplot.py", line 685, in <module>

    RunMain()
  File "C:\Python27\Lib\site-packages\svnplot\svnplot.py", line 682, in RunMain
    svnplot.AllGraphs(graphdir, options.searchpath, options.thumbsize, options.m
axdircount)
  File "C:\Python27\Lib\site-packages\svnplot\svnplot.py", line 247, in AllGraph
s
    graphParamDict = self._getGraphParamDict( thumbsize)
  File "C:\Python27\Lib\site-packages\svnplot\svnplot.py", line 572, in _getGrap
hParamDict
    graphParamDict["TagCloud"] = self.TagCloud()
  File "C:\Python27\Lib\site-packages\svnplot\svnplotbase.py", line 163, in TagC
loud
    tagData = [{ 'text':str(x), 'count':freq} for x, freq in tagWordList]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 3:
ordinal not in range(128)

...................................

Is there already a fix?

```

Original comment by `Har00n...@gmail.com` on 13 Jan 2015 at 10:03

**Comment by GoogleCodeExporter** [comment]
```
Done the fixes in the default branch. Please download the zip file 'tip' from 
the bitbucket and see if the problem is fixed.
```

Original comment by `nitinbh...@gmail.com` on 1 Feb 2015 at 3:25
